//! Rendering the verification skill from accepted records: `SKILL.md`, the
//! rule files, the pstack feature map, the versioned source document and the
//! journal. Deterministic: the same accepted agreement renders the same bytes.

use std::fmt::Write as _;

use serde::Serialize;
use serde_json::json;

use crate::agreement::AgreementState;
use crate::domain::{Feature, RecordBody, RecordId, Rule, VerificationMap};
use crate::feature_map;
use crate::projection;

/// Schema of the source document the Markdown is rendered from.
pub const VERIFY_SCHEMA: &str = "whetstone.verify.v1";

/// `whetstone.verify.v1`: the skill's source of truth, from accepted records.
/// pstack's Markdown layout is rendered from it by `crate::feature_map`, the
/// adapter; a pstack format change breaks the adapter's round-trip test,
/// never this document.
#[derive(Debug, Clone, Serialize)]
pub struct VerifyDocument {
    pub schema: &'static str,
    pub app: String,
    pub agreement: String,
    pub mission: Option<String>,
    pub principles: Vec<String>,
    pub map: VerificationMap,
    pub features: Vec<VerifyFeature>,
    pub rules: Vec<VerifyRule>,
}

#[derive(Debug, Clone, Serialize)]
pub struct VerifyFeature {
    pub id: RecordId,
    pub revision: u64,
    pub feature: Feature,
    pub proven_by: Vec<RecordId>,
}

#[derive(Debug, Clone, Serialize)]
pub struct VerifyRule {
    pub id: RecordId,
    pub revision: u64,
    pub rule: Rule,
}

pub fn verify_document(state: &AgreementState, app: &str, map: &VerificationMap) -> VerifyDocument {
    VerifyDocument {
        schema: VERIFY_SCHEMA,
        app: app.into(),
        agreement: state.in_force_digest(),
        mission: match in_force_body(state, projection::MISSION_ID) {
            Some(RecordBody::Mission(mission)) => Some(mission.statement.clone()),
            _ => None,
        },
        principles: state
            .in_force_matching(|body| matches!(body, RecordBody::Principle(_)))
            .into_iter()
            .map(projection::record_title)
            .collect(),
        map: map.clone(),
        features: features(state)
            .into_iter()
            .map(|(id, feature)| VerifyFeature {
                revision: state.in_force(&id).map_or(0, |record| record.revision),
                proven_by: crate::proof::proving_rules(state, &id, &feature),
                id,
                feature,
            })
            .collect(),
        rules: crate::proof::rule_ids(state)
            .into_iter()
            .filter_map(|id| {
                let record = state.in_force(&id)?;
                let rule = record.body.rule_view()?.into_owned();
                Some(VerifyRule {
                    revision: record.revision,
                    id,
                    rule,
                })
            })
            .collect(),
    }
}

pub(crate) fn in_force_body<'a>(state: &'a AgreementState, id: &str) -> Option<&'a RecordBody> {
    RecordId::new(id)
        .ok()
        .and_then(|id| state.in_force(&id))
        .map(|record| &record.body)
}

pub(crate) fn title_of(state: &AgreementState, id: &RecordId) -> String {
    state
        .in_force(id)
        .map_or_else(|| id.as_str().to_string(), projection::record_title)
}

pub(crate) fn features(state: &AgreementState) -> Vec<(RecordId, Feature)> {
    let mut result = state
        .agreement_ids(|body| matches!(body, RecordBody::Feature(_)))
        .into_iter()
        .filter_map(|id| match state.in_force(&id).map(|record| &record.body) {
            Some(RecordBody::Feature(feature)) => Some((id, feature.clone())),
            _ => None,
        })
        .collect::<Vec<_>>();
    result.sort_by(|left, right| {
        (
            left.1.area.as_str(),
            left.1.sweep_order,
            left.1.name.as_str(),
        )
            .cmp(&(
                right.1.area.as_str(),
                right.1.sweep_order,
                right.1.name.as_str(),
            ))
    });
    result
}

pub(crate) fn skill_markdown(
    state: &AgreementState,
    app: &str,
    config: &serde_json::Value,
    header: &str,
    map: &crate::domain::VerificationMap,
) -> String {
    let driver = feature_map::DRIVER_COMMAND;
    let mut out = String::new();
    let _ = writeln!(out, "---");
    let _ = writeln!(out, "name: verify-{app}");
    let _ = writeln!(
        out,
        "description: \"Launch, drive and prove {app} the way a user does, and know why each feature exists. Use before claiming a change works, to reproduce a report, or to understand the project's intent. Generated by Whetstone from the accepted agreement; a pstack verification skill.\""
    );
    let _ = writeln!(out, "---\n");
    out.push_str(header);
    let _ = writeln!(out, "\n# Verify {app}\n");
    let _ = writeln!(
        out,
        "This skill is a projection of the project's accepted agreement. It tells you why the project exists, how to reach and drive every mapped feature, and what evidence proves it works. Read the one feature file for the change under test, not the whole map.\n"
    );
    let _ = writeln!(out, "## Why this project exists\n");
    if let Some(RecordBody::Mission(mission)) = in_force_body(state, projection::MISSION_ID) {
        let _ = writeln!(out, "**Mission.** {}\n", mission.statement);
    }
    let principles = state.in_force_matching(|body| matches!(body, RecordBody::Principle(_)));
    if !principles.is_empty() {
        let _ = writeln!(
            out,
            "**Principles** decide between options when a rule is silent:\n"
        );
        for record in principles {
            if let RecordBody::Principle(principle) = &record.body {
                let source = match &principle.source {
                    crate::domain::PrincipleSource::Pstack { id, .. } => {
                        format!(" (pstack `principle-{id}`)")
                    }
                    _ => String::new(),
                };
                let _ = writeln!(out, "- {}{source}", principle.statement);
            }
        }
        out.push('\n');
    }
    let _ = writeln!(
        out,
        "The durable \"why\" is the decision history: [`JOURNAL.md`](JOURNAL.md) here, and `wh dash --json` (`data.changelog`, or `wh dash --trail` for a show-me-your-work TSV). Read it before guessing at intent.\n"
    );
    let surface = config
        .get("surface")
        .and_then(serde_json::Value::as_str)
        .unwrap_or("cli");
    let _ = writeln!(out, "## Launch\n");
    let _ = writeln!(
        out,
        "The driver owns launch and teardown for the `{surface}` surface; its configuration is `whetstone/verify/driver.json`. Each launch gets its own port and data directory, so two checkouts never share an instance.\n\n```bash\n{driver} launch --dry-run   # what would start\n{driver} launch             # start and wait until ready\n```\n"
    );
    let _ = writeln!(out, "## Doctor\n");
    let _ = writeln!(
        out,
        "Run this first, again after any failed drive, and whenever anything looks off. A drive against a stale build or an unhealthy instance is not evidence. A stale build is fixed by the build step in the map's baseline preconditions ([`features/README.md`](features/README.md)); then run doctor again.\n\n```bash\n{driver} doctor --json\n```\n"
    );
    let _ = writeln!(out, "## Drive\n");
    let _ = writeln!(
        out,
        "The driver speaks pstack's control-adapter vocabulary: `doctor`, `launch`, `drive`, `inspect`, `screenshot`, `cleanup`, with `prove` as the composite `wh check` uses. Steps run in one session with evidence after each. Prefer stable handles (ids, ARIA labels, data attributes) over text, and text over coordinates.\n\n```bash\n{driver} drive \"open /\" \"expect text=<something visible>\" --json\n{driver} inspect / --json          # read-only: title, headings, landmarks, visible text\n{driver} screenshot / --json       # capture the current state of a path\n{driver} drive \"open /\" \"click <selector>\" \"inspect after-click\" --json   # state after interactions\n{driver} help                      # every step and flag\n```\n\nIf cursor-team-kit's `control-ui` or `control-cli` is installed you may drive with it instead; the evidence rules below still apply.\n"
    );
    let _ = writeln!(out, "## Evidence\n");
    let _ = writeln!(
        out,
        "`wh check` runs every rule and stores evidence (logs, screenshots, transcripts) in the private evidence directory it prints; cleanup never deletes it. A proof must:\n\n- exercise the production user path, not internal setters or test-only endpoints;\n- cover every reachable entry point the feature file lists, and the success, cancel, error, empty and persistence paths the change can affect;\n- show the action and the resulting state, and verify side effects (files, requests, stored records), not just pixels;\n- use mocks only behind a production boundary that already isolates the external system.\n\nAn unreachable path is reported with its concrete prerequisite (account, entitlement, OS), never skipped silently. A pass without evidence is unknown, never green.\n"
    );
    let _ = writeln!(out, "## Cleanup\n");
    let _ = writeln!(
        out,
        "```bash\n{driver} cleanup --dry-run   # what would stop\n{driver} cleanup             # stops only what the driver started; evidence stays\n```\n"
    );
    let _ = writeln!(out, "## Helpers\n");
    let _ = writeln!(
        out,
        "- `wh` is the Whetstone CLI (the `whetstone` binary). If neither name is on PATH, stop and ask the owner where it is installed; never substitute another tool for a gate.\n- `{driver}` is executable with Node 22 and has no dependencies; `{driver} help` documents every command. `wh check` launches its own isolated instance, so an instance you launched for exploring can keep running.\n- `wh check --feature <id>` proves one feature through its accepted drive steps and records a receipt. To prove what your change does, add change-specific assertions: `wh check --feature <id> --step \"expect text=<new behaviour>\" --step \"screenshot after-change\"`; they run after the accepted steps in the same session and the receipt records them with their evidence.\n- `wh check --changed` proves the features whose entry points your uncommitted changes touch; for committed work add `--base <revision>` (for example `--base origin/main`). `wh check --sweep` drives every feature in the order below.\n- Exit codes (the JSON `state`): 0 success, 1 violated, 3 unknown, 4 unavailable, 5 needs decision, 6 needs input, 7 stale (resume with the returned revision and token), 8 conflict. A dry run exits 5 because nothing ran, and so does recording a draft, because the owner decides next.\n- `wh check --json` lists what it recorded: `data.gate_receipts` (one per gate, bound to its evidence under `data.evidence_root`/`data.run_id`) and `data.receipt_record` (the repository scan, when it ran).\n- A change can move behaviour that several feature files describe. `wh check --changed --dry-run` (with `--base` for committed work) lists every feature whose entry points the change touches in `selection.features_affected`; a shared file flags every feature that lists it, so read each one and keep those whose behaviour moved. Search `features/` for the old wording (the change's diff shows it) before you call the map current.\n- Change-specific `--step` assertions prove the change once. Assertions that must keep holding belong in the feature's drive steps: propose them as a map correction, and until the owner accepts it, prove them with `--feature <id> --step ...` before handing off.\n- Before handing off, run `wh check --changed --host <this host>` (claude, cursor, codex or agents): it proves what the change touched and records which revision of this skill you used. With the host's hooks installed this runs at every stop, covering what you committed since the session began, and returns failures to you; the same failure after two repairs raises a hand instead of a third attempt.\n- A Jev question sends only the unit it needs (one hunk, file or commit message), after redaction; a rule marked local-only never leaves the machine.\n"
    );
    let _ = writeln!(out, "## Rules\n");
    let rule_records = crate::proof::rule_ids(state)
        .into_iter()
        .filter_map(|id| state.in_force(&id).map(|record| (id, record)))
        .filter_map(|(id, record)| record.body.rule_view().map(|rule| (id, rule.into_owned())))
        .collect::<Vec<_>>();
    if rule_records.is_empty() {
        let _ = writeln!(out, "No rule is in force yet.\n");
    } else {
        let _ = writeln!(
            out,
            "Each rule has one strength and one enforcer. Never weaken, skip or edit a rule to pass it: propose a change with `wh change --kind rule` for the owner to accept. Each rule is also a file in [`rules/`](rules/) you may edit and return with `wh init --action import --from <this skill directory>`.\n"
        );
        for (strength, label, meaning) in [
            (crate::domain::Strength::Must, "Must", "blocks the commit, push or CI check until it holds; only a mechanical pass, a proof or a review attestation passes it"),
            (crate::domain::Strength::Should, "Should", "flags for repair; the owner may accept or dismiss the flag"),
            (crate::domain::Strength::Advisory, "Advisory", "shown to you and the owner; never blocks"),
        ] {
            let matching = rule_records
                .iter()
                .filter(|(_, rule)| rule.strength == strength)
                .collect::<Vec<_>>();
            if matching.is_empty() {
                continue;
            }
            let _ = writeln!(out, "### {label} ({meaning})\n");
            for (id, rule) in matching {
                let (mechanism, command) = crate::gates::mechanism_label(rule);
                let _ = writeln!(
                    out,
                    "- **{}** — {mechanism}: `{command}`; runs at {}.{}{} Recheck with `wh check --rule {}`.",
                    rule.statement.trim_end_matches('.'),
                    projection::runs_at(rule),
                    if rule.raises_hand_on(crate::domain::HandRaiseTrigger::Flag) {
                        " A flag is the owner's call: raise a hand instead of repairing."
                    } else {
                        ""
                    },
                    if rule.privacy.local_only {
                        " Local-only: Jev is never asked; a review attests it."
                    } else {
                        ""
                    },
                    id.as_str()
                );
            }
            out.push('\n');
        }
    }
    let _ = writeln!(out, "## Before you build\n");
    let _ = writeln!(
        out,
        "Brief yourself before writing code, so you reuse what exists and write nothing the task did not ask for:\n\n1. Run pstack's `/how` for how the area works, `/why` for why it is built that way (start from `JOURNAL.md` and `wh dash --json`), and `/blast-radius` for what the change could break.\n2. Name the existing code, components and design tokens you will reuse. Do not add a helper, component or test until you have checked one does not exist and the task asks for it.\n3. Record the brief: `wh check --brief --area <feature id or path> --skill how --skill why --skill blast-radius --reuse \"<thing>\" --risk \"<what could break>\" --notes \"<summary>\"`. A must rule with a brief enforcer treats a change without one as missing evidence.\n\nAfter each bounded edit run `wh check --changed` (add `--base <ref>` for committed work), repair the smallest thing, and recheck. The Git hooks run the same rules at commit and push; CI runs them as the required `whetstone/policy` check.\n"
    );
    let _ = writeln!(out, "## Raise a hand\n");
    let _ = writeln!(
        out,
        "Stop and ask instead of guessing when:\n\n- a must rule's enforcer is unknown or unavailable;\n- the same finding survives a second repair;\n- the change touches an area a must rule reserves for the owner (for example a public API);\n- a Jev answer is low confidence;\n- the spec is too vague to satisfy the rules.\n\nRaise it with `wh check --raise-hand --question \"<the one decision needed>\" --tried \"<what you tried>\" --recommend \"<what you recommend>\" --trigger <low_confidence|second_failed_repair|must_rule_area|vague_spec|rule_flag|unavailable> [--rule <id>]`. It files a Beads issue labelled `human` (the owner sees it in `bd human list` and the dashboard's Requests view). Then take other ready work (`bd ready`); do not wait and do not guess. Another agent may advise but cannot decide for the owner.\n"
    );
    let _ = writeln!(out, "## Feature map\n");
    let _ = writeln!(
        out,
        "[`features/README.md`](features/README.md) lists every mapped feature in sweep order. Each feature file follows pstack's entry contract (four sections: Sub-features; How to get to it (user POV); Driving it with <harness>; Gotchas) and carries its record id, why it exists, links, proving rules and drift in frontmatter.\n\nWhen behaviour moves, correct the map in the same change. Edit the affected feature files in this directory, then run `wh init --action import --from <this skill directory>`: each edited feature becomes a private draft with an exact before/after, and accepting it (`wh change --accept <proposal>`) is the owner's call. `wh init --action wire` regenerates this directory from accepted records, so after an import it shows the accepted version again: the correction is not lost, it waits as a draft (`wh dash` lists it) until the owner accepts it.\n\nThe same draft from the command line: `wh change --json --request-id <id> --kind feature --record-id <feature id> --content \"<feature name>\" --definition '{{\"type\":\"feature\",\"summary\":\"...\",\"area\":\"...\",\"user_path\":\"...\",\"proof\":\"...\",\"drive_steps\":[...],\"gotchas\":[...],\"entry_points\":[...]}}' --rationale \"<why>\"` answers with `expected_revision` and `resume_token`; repeat the identical command with `--expected-revision <n> --resume <token>` to record the draft (`--preview` shows the exact before/after first). The definition replaces the whole feature, so start from the `current_record` the first response returns; editing the file and importing avoids this.\n"
    );
    let _ = writeln!(out, "## Judgment skills\n");
    let _ = writeln!(
        out,
        "Whetstone owns the deterministic half: records, rules, receipts, the sweep and map hygiene. pstack's skills carry the judgment and read this project's records first as the \"why\" source; Whetstone never reimplements them.\n\n- `how`, `why` and `blast-radius` brief you before building (see above).\n- `interrogate` reviews a change; for a review-enforced rule, record its verdict with `wh check --attest <rule> --verdict pass|fail --reviewer interrogate --notes \"<summary>\"`.\n- `reflect` reviews a finished run; its edits to `rules/` and `features/` return as drafts through `wh init --action import`.\n- `maintain-verification-skill` is the periodic maintenance pass for this skill (see below).\n"
    );
    let _ = writeln!(out, "## Maintenance\n");
    let _ = writeln!(
        out,
        "Run pstack's `/maintain-verification-skill` on this directory as the periodic pass. Its edit scope is this skill directory only (SKILL.md and `features/`); it never edits product code. Classify each difference as doc drift, harness gap or product gap:\n\n- doc drift and map corrections: edit the feature files here, then return them through Whetstone with `wh init --action import --from <this directory>`, which records each edited feature as a private draft with an exact before/after for the owner to accept (`wh change --accept <proposal>`). Regenerate with `wh init --action wire` afterwards (it rewires the hosts wired before); hand edits are otherwise overwritten.\n- harness gaps: fix `whetstone/verify/drive.mjs` or `driver.json` (team-owned) and re-drive.\n- product gaps: file them in the tracker (Beads) with the evidence paths; never paper over them in the map.\n\nThe deterministic half runs with `wh check --sweep`: one receipt per feature (proven, failed with the step, unreachable with the prerequisite, or skipped with the reason) plus hygiene findings. Report the pass outcome (clean, changed or blocked) with `wh check --maintain-outcome <clean|changed|blocked> --maintain-evidence <run notes file or PR URL> --json`; without the evidence the outcome is recorded as unknown.\n"
    );
    if !map.skill_notes.is_empty() {
        let _ = writeln!(out, "## Imported notes\n");
        let _ = writeln!(
            out,
            "Kept verbatim from the imported verification skill; fold them into the records above with `wh change` and they disappear from here.\n"
        );
        for note in &map.skill_notes {
            let _ = writeln!(out, "### {}\n\n{}\n", note.section, note.text.trim());
        }
    }
    out
}

/// The map conventions in force, or defaults derived from the driver config.
pub(crate) fn map_conventions(
    state: &AgreementState,
    app: &str,
    config: &serde_json::Value,
) -> crate::domain::VerificationMap {
    state
        .in_force_matching(|body| matches!(body, RecordBody::VerificationMap(_)))
        .into_iter()
        .find_map(|record| match &record.body {
            RecordBody::VerificationMap(map) => Some(map.clone()),
            _ => None,
        })
        .unwrap_or_else(|| {
            feature_map::default_map(
                app,
                config
                    .get("surface")
                    .and_then(serde_json::Value::as_str)
                    .unwrap_or("cli"),
            )
        })
}

pub(crate) fn features_readme(
    state: &AgreementState,
    map: &crate::domain::VerificationMap,
    header: &str,
) -> String {
    let features = features(state);
    let refs = features
        .iter()
        .map(|(id, feature)| (id, feature))
        .collect::<Vec<_>>();
    format!("{header}{}", feature_map::render_readme(map, &refs))
}

/// Why a feature exists, in one line, from the records it links.
fn why_line(state: &AgreementState, feature: &Feature) -> String {
    let serves = feature
        .serves
        .iter()
        .map(|id| title_of(state, id))
        .collect::<Vec<_>>();
    let constrained = feature
        .constrained_by
        .iter()
        .map(|id| title_of(state, id))
        .collect::<Vec<_>>();
    match (serves.is_empty(), constrained.is_empty()) {
        (true, true) => {
            "No mission or principle is linked yet; ask the owner why this feature exists.".into()
        }
        (false, true) => format!("Serves: {}", serves.join("; ")),
        (true, false) => format!("Constrained by: {}", constrained.join("; ")),
        (false, false) => format!(
            "Serves: {}. Constrained by: {}",
            serves.join("; "),
            constrained.join("; ")
        ),
    }
}

pub(crate) fn feature_markdown(
    state: &AgreementState,
    id: &RecordId,
    feature: &Feature,
    agreement_digest: &str,
    proof: &crate::proof::FeatureProof,
) -> String {
    let revision = state.in_force(id).map_or(0, |record| record.revision);
    let mut frontmatter = String::new();
    for (key, value) in [
        ("record", json!(id.as_str())),
        ("revision", json!(revision)),
        ("area", json!(feature.area)),
        ("sweep_order", json!(feature.sweep_order)),
        ("why", json!(why_line(state, feature))),
        ("serves", json!(feature.serves)),
        ("constrained_by", json!(feature.constrained_by)),
        ("proven_by", json!(feature.proven_by)),
        ("last_proven", json!(proof.last_proven)),
        ("drift", json!(proof.drift)),
        ("entry_points", json!(feature.entry_points)),
        ("drive_steps", json!(feature.drive_steps)),
        ("agreement", json!(agreement_digest)),
        (
            "generated_by",
            json!("Whetstone; edit here and return with `wh init --action import`, or use `wh change --kind feature`"),
        ),
    ] {
        frontmatter.push_str(&feature_map::frontmatter_line(key, &value));
    }
    feature_map::render_feature_file(&feature_map::RenderFeature {
        id,
        feature,
        frontmatter: Some(frontmatter),
    })
}

pub(crate) fn journal_markdown(state: &AgreementState, header: &str) -> String {
    let mut out = String::new();
    out.push_str(header);
    let _ = writeln!(out, "\n# Journal\n");
    let _ = writeln!(
        out,
        "How the agreement evolved, newest first. Only accepted revisions and their superseded predecessors are listed; private drafts are not.\n"
    );
    let mut entries = state
        .records()
        .iter()
        .filter(|record| crate::agreement::is_agreement_body(&record.body))
        .filter(|record| state.lifecycle_of(record) == crate::agreement::Lifecycle::Accepted)
        .collect::<Vec<_>>();
    entries.sort_by(|left, right| {
        right
            .provenance
            .recorded_at
            .cmp(&left.provenance.recorded_at)
            .then_with(|| left.id.cmp(&right.id))
    });
    for record in entries.into_iter().take(200) {
        let kind = match &record.body {
            RecordBody::Mission(_) => "mission",
            RecordBody::Principle(_) => "principle",
            RecordBody::Rule(_) | RecordBody::Standard(_) | RecordBody::Guidance(_) => "rule",
            RecordBody::Feature(_) => "feature",
            RecordBody::VerificationMap(_) => "map",
            _ => "record",
        };
        let status = if state.is_superseded(record) {
            " (superseded)"
        } else {
            ""
        };
        let why = state
            .proposal_for(record)
            .and_then(|proposal| match &proposal.body {
                RecordBody::Proposal(body) => body
                    .rationale
                    .lines()
                    .find_map(|line| line.strip_prefix("Rationale: "))
                    .map(str::to_owned),
                _ => None,
            });
        let _ = writeln!(
            out,
            "- {} · {} v{}{status}: {}{}",
            record
                .provenance
                .recorded_at
                .get(..10)
                .unwrap_or(&record.provenance.recorded_at),
            projection::kind_label(kind),
            record.revision,
            projection::record_title(record),
            why.map(|why| format!(" — {why}")).unwrap_or_default()
        );
    }
    out
}
