//! One editable Markdown file per rule in the generated skill
//! (`rules/<slug>.md`), so pstack's `/reflect` and people can edit a rule's
//! wording, examples or enforcer and return the edit with
//! `wh init --action import`: an edited file becomes one draft with an exact
//! before and after, and an unchanged file records nothing.
//!
//! Format: JSON-valued frontmatter (record, revision, strength, enforcer,
//! source, paths, hand_raise, privacy), an H1 with the statement, the
//! rationale, then `## Examples` with one `### Flag: <reason>` or
//! `### Pass: <reason>` per example, an optional `Path:` line and the input
//! in a fenced block.

use std::collections::BTreeMap;

use serde_json::{json, Value};

use crate::domain::{
    Enforcer, ExampleVerdict, HandRaiseTrigger, Privacy, RecordId, Rule, RuleExample, RuleSource,
    Strength, RULE_SCHEMA_V2,
};

pub fn rule_slug(id: &RecordId) -> String {
    id.as_str()
        .trim_start_matches("rule.")
        .trim_start_matches("standard.")
        .chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() || character == '-' {
                character.to_ascii_lowercase()
            } else {
                '-'
            }
        })
        .collect()
}

fn fence(text: &str) -> String {
    let mut ticks = "```".to_string();
    while text.contains(&ticks) {
        ticks.push('`');
    }
    ticks
}

pub fn render_rule_file(id: &RecordId, revision: u64, rule: &Rule, header: &str) -> String {
    let mut out = String::from("---\n");
    for (key, value) in [
        ("record", json!(id.as_str())),
        ("revision", json!(revision)),
        ("strength", json!(rule.strength)),
        ("enforcer", json!(rule.enforcer)),
        ("source", json!(rule.source)),
        ("paths", json!(rule.paths)),
        ("hand_raise", json!(rule.hand_raise)),
        ("privacy", json!(rule.privacy)),
    ] {
        out.push_str(&crate::feature_map::frontmatter_line(key, &value));
    }
    out.push_str("---\n\n");
    out.push_str(header);
    out.push_str(&format!(
        "\n# {}\n\n{}\n",
        rule.statement.trim(),
        rule.rationale.trim()
    ));
    if !rule.examples.is_empty() {
        out.push_str("\n## Examples\n");
        for example in &rule.examples {
            let verdict = match example.expected {
                ExampleVerdict::Flag => "Flag",
                ExampleVerdict::Pass => "Pass",
            };
            out.push_str(&format!("\n### {verdict}: {}\n\n", example.reason.trim()));
            if let Some(path) = &example.path {
                out.push_str(&format!("Path: `{path}`\n\n"));
            }
            let ticks = fence(&example.input);
            out.push_str(&format!(
                "{ticks}text\n{}\n{ticks}\n",
                example.input.trim_end()
            ));
        }
    }
    out
}

/// A rule file read back: the record it names and the rule it now says.
pub struct ParsedRule {
    pub id: RecordId,
    pub rule: Rule,
}

pub fn parse_rule_file(text: &str) -> Result<ParsedRule, String> {
    let body = text
        .strip_prefix("---\n")
        .ok_or("a rule file starts with frontmatter")?;
    let end = body
        .find("\n---\n")
        .ok_or("the rule file's frontmatter is not closed")?;
    let mut front = BTreeMap::<String, Value>::new();
    for line in body[..end].lines() {
        if let Some((key, value)) = line.split_once(':') {
            let value = serde_json::from_str::<Value>(value.trim())
                .map_err(|error| format!("frontmatter {key} is not JSON: {error}"))?;
            front.insert(key.trim().to_string(), value);
        }
    }
    let field = |key: &str| front.get(key).cloned().unwrap_or(Value::Null);
    let id = field("record")
        .as_str()
        .ok_or("the rule file names no record")
        .and_then(|id| RecordId::new(id).map_err(|_| "the record id is not valid"))?;
    let strength: Strength =
        serde_json::from_value(field("strength")).map_err(|error| format!("strength: {error}"))?;
    let enforcer: Enforcer =
        serde_json::from_value(field("enforcer")).map_err(|error| format!("enforcer: {error}"))?;
    let source: RuleSource =
        serde_json::from_value(field("source")).map_err(|error| format!("source: {error}"))?;
    let paths: Vec<String> = serde_json::from_value(field("paths")).unwrap_or_default();
    let hand_raise: Vec<HandRaiseTrigger> =
        serde_json::from_value(field("hand_raise")).unwrap_or_default();
    let privacy: Privacy = serde_json::from_value(field("privacy")).unwrap_or_default();
    let rest = &body[end + "\n---\n".len()..];
    let mut lines = rest
        .lines()
        .filter(|line| !line.starts_with("<!-- Generated by Whetstone"))
        .peekable();
    let mut statement = None;
    let mut rationale = Vec::new();
    let mut examples = Vec::new();
    let mut in_examples = false;
    while let Some(line) = lines.next() {
        if statement.is_none() {
            if let Some(title) = line.strip_prefix("# ") {
                statement = Some(title.trim().to_string());
            }
            continue;
        }
        if line.trim() == "## Examples" {
            in_examples = true;
            continue;
        }
        if !in_examples {
            rationale.push(line);
            continue;
        }
        let Some(heading) = line.strip_prefix("### ") else {
            continue;
        };
        let (verdict, reason) = heading.split_once(':').ok_or_else(|| {
            format!("example heading `{heading}` is not `Flag: <reason>` or `Pass: <reason>`")
        })?;
        let expected = match verdict.trim() {
            "Flag" => ExampleVerdict::Flag,
            "Pass" => ExampleVerdict::Pass,
            other => return Err(format!("example verdict `{other}` is not Flag or Pass")),
        };
        let mut path = None;
        let mut input = Vec::new();
        let mut open: Option<String> = None;
        while let Some(line) = lines.peek().copied() {
            if open.is_none() && line.starts_with("### ") {
                break;
            }
            lines.next();
            match &open {
                None if line.starts_with("Path:") => {
                    path = Some(line["Path:".len()..].trim().trim_matches('`').to_string());
                }
                None if line.starts_with("```") => {
                    open = Some(
                        line.chars()
                            .take_while(|character| *character == '`')
                            .collect(),
                    );
                }
                Some(ticks) if line.trim_end() == ticks => break,
                Some(_) => input.push(line),
                None => {}
            }
        }
        examples.push(RuleExample {
            input: input.join("\n"),
            expected,
            reason: reason.trim().to_string(),
            path,
        });
    }
    let rule = Rule {
        schema: RULE_SCHEMA_V2.into(),
        statement: statement.ok_or("the rule file has no `# <statement>` title")?,
        rationale: rationale.join("\n").trim().to_string(),
        strength,
        enforcer,
        examples,
        source,
        paths,
        hand_raise,
        privacy,
    };
    rule.validate()
        .map_err(|error| format!("the rule is not valid: {error}"))?;
    Ok(ParsedRule { id, rule })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rule_files_round_trip_and_an_edit_changes_only_what_changed() {
        let rule = crate::starter::starters(std::path::Path::new("/nonexistent"))
            .into_iter()
            .find(|starter| starter.id == crate::starter::TESTS_ONLY_WHEN_ASKED)
            .expect("starter")
            .rule;
        let id = RecordId::new(crate::starter::TESTS_ONLY_WHEN_ASKED).expect("id");
        let text = render_rule_file(
            &id,
            1,
            &rule,
            "<!-- Generated by Whetstone from agreement x. -->\n",
        );
        let parsed = parse_rule_file(&text).expect("parse");
        assert_eq!(parsed.id, id);
        assert_eq!(parsed.rule, rule);
        let edited = text.replace("\"should\"", "\"must\"");
        let parsed = parse_rule_file(&edited).expect("parse edit");
        assert_eq!(parsed.rule.strength, Strength::Must);
        assert_eq!(parsed.rule.examples, rule.examples);
        assert_eq!(rule_slug(&id), "tests-only-when-asked");
    }
}
