#!/usr/bin/env python3
"""Generate native test files and linter configurations from approved rules.

Reads approved rules from whetstone/rules/**/*.yaml and generates:
- Python: pytest files + ruff config overlay
- TypeScript: vitest files + biome config overlay
- Rust: cargo test files + clippy config overlay

Usage:
    python3 scripts/generate-tests.py
    python3 scripts/generate-tests.py --lang python --dry-run
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import textwrap
from datetime import datetime, timezone
from pathlib import Path

try:
    import yaml
except ImportError:
    yaml = None  # type: ignore[assignment]


# --- YAML loading ---


def load_yaml_file(filepath: Path) -> dict | None:
    """Load and parse a YAML file."""
    try:
        text = filepath.read_text()
        if yaml:
            return yaml.safe_load(text)
        raise ImportError("PyYAML is required. Install with: pip install pyyaml")
    except Exception:
        return None


# --- Rule loading ---


def load_rules(
    rules_dir: Path, lang_filter: str | None = None
) -> tuple[list[dict], list[str], int]:
    """Load approved rules, optionally filtered by language."""
    approved: list[dict] = []
    warnings: list[str] = []
    skipped = 0

    if not rules_dir.exists():
        return approved, ["Rules directory not found"], 0

    for yaml_file in sorted(rules_dir.rglob("*.yaml")):
        data = load_yaml_file(yaml_file)
        if not data:
            warnings.append(f"Failed to parse: {yaml_file}")
            continue

        source = data.get("source", {})
        dep_name = source.get("name", yaml_file.stem)
        language = _infer_language(yaml_file, source)

        if lang_filter and language != lang_filter:
            continue

        for rule in data.get("rules", []):
            if not rule.get("approved", False):
                skipped += 1
                continue
            rule["_language"] = language
            rule["_dep_name"] = dep_name
            approved.append(rule)

    return approved, warnings, skipped


def _infer_language(filepath: Path, source: dict) -> str:
    """Infer language from path or source."""
    path_str = str(filepath)
    if "/python/" in path_str:
        return "python"
    if "/typescript/" in path_str:
        return "typescript"
    if "/rust/" in path_str:
        return "rust"
    return source.get("language", "generic")


# --- Test file header ---


def _test_header(rule_id: str, source_url: str) -> str:
    """Generate a standard header comment."""
    return f"""# Rule: {rule_id}
# Source: {source_url}
# Generated by Whetstone — do not edit manually
"""


def _test_header_ts(rule_id: str, source_url: str) -> str:
    return f"""// Rule: {rule_id}
// Source: {source_url}
// Generated by Whetstone — do not edit manually
"""


def _test_header_rs(rule_id: str, source_url: str) -> str:
    return f"""// Rule: {rule_id}
// Source: {source_url}
// Generated by Whetstone — do not edit manually
"""


# --- Python test generation ---


def _sanitize_name(name: str) -> str:
    """Convert a rule ID to a valid Python/Rust identifier."""
    return re.sub(r"[^a-zA-Z0-9]", "_", name).strip("_").lower()


def generate_python_test(rule: dict) -> str:
    """Generate a pytest test file for a Python rule."""
    rule_id = rule.get("id", "unknown")
    source_url = rule.get("source_url", "")
    description = rule.get("description", "").strip()
    dep_name = rule.get("_dep_name", "unknown")
    signals = rule.get("signals", [])

    header = _test_header(rule_id, source_url)
    func_name = _sanitize_name(rule_id)

    # Determine which imports we need based on signal strategies
    has_ast = any(s.get("strategy") == "ast" for s in signals)
    has_pattern = any(s.get("strategy") == "pattern" for s in signals)

    imports: list[str] = []
    if has_ast:
        imports.append("import ast")
    if has_pattern:
        imports.append("import re")
    imports.extend(["import glob", "import os"])

    # Build signal checks
    checks: list[str] = []
    for signal in signals:
        strategy = signal.get("strategy", "")
        sig_desc = signal.get("description", "")

        if strategy == "ast":
            checks.append(_generate_ast_check(sig_desc, dep_name))
        elif strategy == "pattern":
            checks.append(_generate_pattern_check(sig_desc))
        elif strategy == "lint_proxy":
            continue  # Handled in linter config, not test
        elif strategy == "ai":
            checks.append(f"        # AI signal (not auto-testable): {sig_desc}")

    if not checks:
        checks.append(f"        # TODO: Implement signal checks for: {description}")
        checks.append("        pass")

    check_body = "\n".join(checks)

    return f"""{header}
{chr(10).join(imports)}


def test_{func_name}():
    \"\"\"{description}\"\"\"
    violations = []

    for filepath in glob.glob('src/**/*.py', recursive=True):
        if 'whetstone/' in filepath:
            continue
        try:
            with open(filepath) as f:
                source = f.read()
        except (OSError, UnicodeDecodeError):
            continue

{check_body}

    assert not violations, (
        f"{{len(violations)}} violation(s) found for {rule_id}:\\n"
        + "\\n".join(violations)
    )
"""


def _generate_ast_check(description: str, dep_name: str) -> str:
    """Generate an AST-based check from signal description."""
    desc_lower = description.lower()
    INDENT = "        "  # 8 spaces — inside the for loop

    # Common patterns: async vs sync functions
    if "async" in desc_lower and ("sync" in desc_lower or "def " in desc_lower):
        lines = [
            "try:",
            "    tree = ast.parse(source)",
            "except SyntaxError:",
            "    continue",
            "",
            "route_decorators = {'get', 'post', 'put', 'delete', 'patch', 'head', 'options'}",
            "for node in ast.walk(tree):",
            "    if isinstance(node, ast.FunctionDef) and not isinstance(node, ast.AsyncFunctionDef):",
            "        for decorator in node.decorator_list:",
            "            dec_name = ''",
            "            if isinstance(decorator, ast.Call):",
            "                if isinstance(decorator.func, ast.Attribute):",
            "                    dec_name = decorator.func.attr",
            "                elif isinstance(decorator.func, ast.Name):",
            "                    dec_name = decorator.func.id",
            "            elif isinstance(decorator, ast.Attribute):",
            "                dec_name = decorator.attr",
            "            elif isinstance(decorator, ast.Name):",
            "                dec_name = decorator.id",
            "            if dec_name in route_decorators:",
            '                violations.append(f"{filepath}:{node.lineno} - {node.name} is sync")',
        ]
        return "\n".join(INDENT + line if line else "" for line in lines)

    # Deprecated function call
    if "deprecated" in desc_lower or "instead of" in desc_lower:
        match = re.search(
            r"(?:uses?|calls?)\s+[`'\"]?(\w+(?:\.\w+)*)[`'\"]?", description
        )
        if match:
            old_name = match.group(1)
            short_name = old_name.split(".")[-1]
            lines = [
                "try:",
                "    tree = ast.parse(source)",
                "except SyntaxError:",
                "    continue",
                "",
                "for node in ast.walk(tree):",
                "    if isinstance(node, ast.Call):",
                "        call_name = ''",
                "        if isinstance(node.func, ast.Attribute):",
                "            call_name = node.func.attr",
                "        elif isinstance(node.func, ast.Name):",
                "            call_name = node.func.id",
                f"        if call_name == '{short_name}':",
                f'            violations.append(f"{{filepath}}:{{node.lineno}} - uses deprecated {old_name}")',
            ]
            return "\n".join(INDENT + line if line else "" for line in lines)

    # Default: generic AST walk with TODO
    lines = [
        "try:",
        "    tree = ast.parse(source)",
        "except SyntaxError:",
        "    continue",
        "",
        f"# TODO: Implement AST check for: {description}",
        "# Walk the AST and check for violations",
        "for node in ast.walk(tree):",
        "    pass  # Add specific checks here",
    ]
    return "\n".join(INDENT + line if line else "" for line in lines)


def _generate_pattern_check(description: str) -> str:
    """Generate a regex-based check from signal description."""
    desc_lower = description.lower()
    INDENT = "        "  # 8 spaces — inside the for loop

    # Try to extract a pattern to search for
    if (
        "deprecated" in desc_lower
        or ".schema()" in description
        or "calls" in desc_lower
    ):
        match = re.search(r"\.(\w+\(\))", description)
        if not match:
            match = re.search(r"[`'\"](\w+(?:\.\w+)*)[`'\"]", description)
        if match:
            raw = match.group(1)
            pattern = re.escape(raw)
            lines = [
                "for i, line in enumerate(source.splitlines(), 1):",
                f"    if re.search(r'{pattern}', line):",
                f'        violations.append(f"{{filepath}}:{{i}} - matches deprecated pattern: {raw}")',
            ]
            return "\n".join(INDENT + line for line in lines)

    # Default: generic pattern check with TODO
    lines = [
        f"# TODO: Implement pattern check for: {description}",
        "# Example:",
        "# for i, line in enumerate(source.splitlines(), 1):",
        "#     if re.search(r'pattern_here', line):",
        '#         violations.append(f"{filepath}:{i} - violation description")',
    ]
    return "\n".join(INDENT + line for line in lines)


def generate_python_conftest(output_dir: Path) -> str:
    """Generate conftest.py with shared fixtures."""
    return f"""# Generated by Whetstone — do not edit manually
# Shared pytest fixtures for Whetstone eval tests

import pytest
import os


@pytest.fixture
def project_python_files():
    \"\"\"Collect all Python files in src/ for analysis.\"\"\"
    files = []
    for root, dirs, filenames in os.walk('src'):
        # Skip whetstone directory
        dirs[:] = [d for d in dirs if d != 'whetstone']
        for filename in filenames:
            if filename.endswith('.py'):
                files.append(os.path.join(root, filename))
    return files
"""


# --- TypeScript test generation ---


def generate_typescript_test(rule: dict) -> str:
    """Generate a vitest test file for a TypeScript rule."""
    rule_id = rule.get("id", "unknown")
    source_url = rule.get("source_url", "")
    description = rule.get("description", "").strip()
    signals = rule.get("signals", [])

    header = _test_header_ts(rule_id, source_url)

    # Build signal checks
    signal_comments: list[str] = []
    for signal in signals:
        strategy = signal.get("strategy", "")
        sig_desc = signal.get("description", "")
        if strategy in ("ast", "pattern"):
            signal_comments.append(f"    // Signal ({strategy}): {sig_desc}")
        elif strategy == "ai":
            signal_comments.append(f"    // AI signal (not auto-testable): {sig_desc}")

    checks = (
        "\n".join(signal_comments)
        if signal_comments
        else "    // TODO: Implement signal checks"
    )

    return f"""{header}

import {{ describe, it, expect }} from 'vitest';
import * as fs from 'fs';
import * as path from 'path';
import {{ globSync }} from 'glob';

describe('{rule_id}', () => {{
  it('{description.replace(chr(39), chr(92) + chr(39))}', () => {{
    const violations: string[] = [];
    const files = globSync('src/**/*.{{ts,tsx}}');

    for (const filepath of files) {{
      if (filepath.includes('whetstone/')) continue;
      const content = fs.readFileSync(filepath, 'utf-8');
      const lines = content.split('\\n');

{checks}

      // TODO: Add file scanning logic based on signals above
    }}

    expect(violations).toEqual([]);
  }});
}});
"""


# --- Rust test generation ---


def generate_rust_test(rule: dict) -> str:
    """Generate a cargo test file for a Rust rule."""
    rule_id = rule.get("id", "unknown")
    source_url = rule.get("source_url", "")
    description = rule.get("description", "").strip()
    func_name = _sanitize_name(rule_id)
    signals = rule.get("signals", [])

    header = _test_header_rs(rule_id, source_url)

    signal_comments: list[str] = []
    for signal in signals:
        strategy = signal.get("strategy", "")
        sig_desc = signal.get("description", "")
        signal_comments.append(f"    // Signal ({strategy}): {sig_desc}")

    checks = (
        "\n".join(signal_comments)
        if signal_comments
        else "    // TODO: Implement signal checks"
    )

    return f"""{header}

#[cfg(test)]
mod {func_name}_tests {{
    use std::fs;
    use std::path::Path;

    fn find_rs_files(dir: &str) -> Vec<String> {{
        let mut files = Vec::new();
        if let Ok(entries) = fs::read_dir(dir) {{
            for entry in entries.flatten() {{
                let path = entry.path();
                if path.is_dir() && !path.to_str().unwrap_or("").contains("whetstone") {{
                    files.extend(find_rs_files(path.to_str().unwrap_or("")));
                }} else if path.extension().map_or(false, |e| e == "rs") {{
                    if let Some(p) = path.to_str() {{
                        files.push(p.to_string());
                    }}
                }}
            }}
        }}
        files
    }}

    #[test]
    fn test_{func_name}() {{
        let violations: Vec<String> = Vec::new();
        let files = find_rs_files("src");

        for filepath in &files {{
            let content = match fs::read_to_string(filepath) {{
                Ok(c) => c,
                Err(_) => continue,
            }};

{checks}

            // TODO: Add content scanning logic based on signals above
        }}

        assert!(
            violations.is_empty(),
            "{{}} violation(s) found for {rule_id}:\\n{{}}",
            violations.len(),
            violations.join("\\n")
        );
    }}
}}
"""


# --- Linter config generation ---


def generate_ruff_config(rules: list[dict]) -> str:
    """Generate ruff.whetstone.toml overlay."""
    lines = [
        "# Generated by Whetstone — do not edit manually",
        "# Ruff configuration overlay for Whetstone rules",
        f"# Last updated: {datetime.now(timezone.utc).strftime('%Y-%m-%d')}",
        "",
        "[lint]",
    ]

    select_rules: list[str] = []
    for rule in rules:
        for signal in rule.get("signals", []):
            if signal.get("strategy") == "lint_proxy":
                # Try to extract ruff rule code from description
                desc = signal.get("description", "")
                match = re.search(r"\b([A-Z]+\d{3,4})\b", desc)
                if match:
                    select_rules.append(match.group(1))

    if select_rules:
        rules_str = ", ".join(f'"{r}"' for r in sorted(set(select_rules)))
        lines.append(f"extend-select = [{rules_str}]")
    else:
        lines.append("# No lint_proxy signals found in rules")
        lines.append("# extend-select = []")

    lines.append("")
    return "\n".join(lines)


def generate_biome_config(rules: list[dict]) -> dict:
    """Generate biome.whetstone.json overlay."""
    config: dict = {
        "$schema": "https://biomejs.dev/schemas/1.9.4/schema.json",
        "_comment": "Generated by Whetstone — do not edit manually",
        "linter": {
            "enabled": True,
            "rules": {},
        },
    }

    for rule in rules:
        for signal in rule.get("signals", []):
            if signal.get("strategy") == "lint_proxy":
                desc = signal.get("description", "")
                # Try to extract biome rule name
                match = re.search(r"\b(no\w+|use\w+)\b", desc)
                if match:
                    rule_name = match.group(1)
                    config["linter"]["rules"][rule_name] = "error"

    return config


def generate_clippy_config(rules: list[dict]) -> str:
    """Generate clippy.whetstone.toml overlay."""
    lines = [
        "# Generated by Whetstone — do not edit manually",
        "# Clippy configuration overlay for Whetstone rules",
        f"# Last updated: {datetime.now(timezone.utc).strftime('%Y-%m-%d')}",
        "",
        "[lints.clippy]",
    ]

    for rule in rules:
        for signal in rule.get("signals", []):
            if signal.get("strategy") == "lint_proxy":
                desc = signal.get("description", "")
                match = re.search(r"\b([\w_]+)\b", desc)
                if match:
                    lines.append(f'{match.group(1)} = "deny"')

    if len(lines) == 5:  # Only header, no rules
        lines.append("# No lint_proxy signals found in rules")

    lines.append("")
    return "\n".join(lines)


# --- Main orchestration ---


def generate_tests(
    project_dir: Path,
    rules_dir: Path | None = None,
    output_dir: Path | None = None,
    lint_dir: Path | None = None,
    lang_filter: str | None = None,
    dry_run: bool = False,
) -> dict:
    """Main test generation logic."""
    if rules_dir is None:
        rules_dir = project_dir / "whetstone" / "rules"
    if output_dir is None:
        output_dir = project_dir / "whetstone" / "evals"
    if lint_dir is None:
        lint_dir = project_dir / "whetstone" / "lint"

    rules, warnings, skipped = load_rules(rules_dir, lang_filter)

    if not rules:
        return {
            "generated": {
                "tests": {"python": [], "typescript": [], "rust": []},
                "lint_configs": [],
            },
            "rules_processed": 0,
            "skipped_unapproved": skipped,
            "warnings": warnings or ["No approved rules found"],
            "next_command": "Extract rules first: run whetstone doctor",
        }

    # Group by language
    by_lang: dict[str, list[dict]] = {"python": [], "typescript": [], "rust": []}
    for rule in rules:
        lang = rule.get("_language", "")
        if lang in by_lang:
            by_lang[lang].append(rule)

    generated_tests: dict[str, list[str]] = {"python": [], "typescript": [], "rust": []}
    generated_lint: list[str] = []

    # --- Python ---
    if by_lang["python"]:
        py_dir = output_dir / "python"
        if not dry_run:
            py_dir.mkdir(parents=True, exist_ok=True)

        for rule in by_lang["python"]:
            rule_id = rule.get("id", "unknown")
            fname = f"test_{_sanitize_name(rule_id)}.py"
            fpath = py_dir / fname

            content = generate_python_test(rule)
            if not dry_run:
                fpath.write_text(content)
            generated_tests["python"].append(str(fpath))

        # conftest.py
        conftest_path = py_dir / "conftest.py"
        if not dry_run:
            conftest_path.write_text(generate_python_conftest(py_dir))

        # Ruff config
        if not dry_run:
            lint_dir.mkdir(parents=True, exist_ok=True)
        ruff_path = lint_dir / "ruff.whetstone.toml"
        ruff_content = generate_ruff_config(by_lang["python"])
        if not dry_run:
            ruff_path.write_text(ruff_content)
        generated_lint.append(str(ruff_path))

    # --- TypeScript ---
    if by_lang["typescript"]:
        ts_dir = output_dir / "typescript"
        if not dry_run:
            ts_dir.mkdir(parents=True, exist_ok=True)

        for rule in by_lang["typescript"]:
            rule_id = rule.get("id", "unknown")
            fname = f"{rule_id.replace('.', '-')}.test.ts"
            fpath = ts_dir / fname

            content = generate_typescript_test(rule)
            if not dry_run:
                fpath.write_text(content)
            generated_tests["typescript"].append(str(fpath))

        # Biome config
        if not dry_run:
            lint_dir.mkdir(parents=True, exist_ok=True)
        biome_path = lint_dir / "biome.whetstone.json"
        biome_config = generate_biome_config(by_lang["typescript"])
        if not dry_run:
            biome_path.write_text(json.dumps(biome_config, indent=2) + "\n")
        generated_lint.append(str(biome_path))

    # --- Rust ---
    if by_lang["rust"]:
        rs_dir = output_dir / "rust"
        if not dry_run:
            rs_dir.mkdir(parents=True, exist_ok=True)

        for rule in by_lang["rust"]:
            rule_id = rule.get("id", "unknown")
            fname = f"whetstone_{_sanitize_name(rule_id)}.rs"
            fpath = rs_dir / fname

            content = generate_rust_test(rule)
            if not dry_run:
                fpath.write_text(content)
            generated_tests["rust"].append(str(fpath))

        # Clippy config
        if not dry_run:
            lint_dir.mkdir(parents=True, exist_ok=True)
        clippy_path = lint_dir / "clippy.whetstone.toml"
        clippy_content = generate_clippy_config(by_lang["rust"])
        if not dry_run:
            clippy_path.write_text(clippy_content)
        generated_lint.append(str(clippy_path))

    # Build appropriate next command based on what was generated
    test_paths = []
    if "python" in by_lang:
        test_paths.append("pytest whetstone/evals/python/")
    if "typescript" in by_lang:
        test_paths.append("npx vitest run whetstone/evals/typescript/")
    if "rust" in by_lang:
        test_paths.append("cargo test --test whetstone")

    if test_paths:
        next_command = "Run tests: " + " && ".join(test_paths)
    else:
        next_command = "Check status: python3 scripts/status.py --project-dir ."

    result: dict = {
        "generated": {
            "tests": generated_tests,
            "lint_configs": generated_lint,
        },
        "rules_processed": len(rules),
        "skipped_unapproved": skipped,
        "next_command": next_command,
    }
    if warnings:
        result["warnings"] = warnings

    return result


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate test files and linter configs from approved Whetstone rules."
    )
    parser.add_argument(
        "--project-dir",
        type=Path,
        default=Path("."),
        help="Project root directory (default: .)",
    )
    parser.add_argument(
        "--rules-dir",
        type=Path,
        help="Rules directory (default: whetstone/rules)",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        help="Test output directory (default: whetstone/evals)",
    )
    parser.add_argument(
        "--lint-dir",
        type=Path,
        help="Lint config output directory (default: whetstone/lint)",
    )
    parser.add_argument(
        "--lang",
        choices=["python", "typescript", "rust"],
        help="Only generate for specified language",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be generated without writing files",
    )
    args = parser.parse_args()

    try:
        result = generate_tests(
            project_dir=args.project_dir,
            rules_dir=args.rules_dir,
            output_dir=args.output_dir,
            lint_dir=args.lint_dir,
            lang_filter=args.lang,
            dry_run=args.dry_run,
        )

        json.dump(result, sys.stdout, indent=2)
        sys.stdout.write("\n")

    except Exception as e:
        json.dump({"error": str(e)}, sys.stdout, indent=2)
        sys.stdout.write("\n")
        sys.exit(1)


if __name__ == "__main__":
    main()
