#!/usr/bin/env python3
"""Generate native test files and linter configurations from approved rules.

Reads approved rules from whetstone/rules/**/*.yaml and generates:
- Python: pytest files + ruff config overlay
- TypeScript: vitest files + biome config overlay
- Rust: cargo test files + clippy config overlay

Usage:
    python3 scripts/generate-tests.py
    python3 scripts/generate-tests.py --lang python --dry-run
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import textwrap
from datetime import datetime, timezone
from pathlib import Path

try:
    import yaml
except ImportError:
    yaml = None  # type: ignore[assignment]


# --- YAML loading ---


def load_yaml_file(filepath: Path) -> dict | None:
    """Load and parse a YAML file."""
    try:
        text = filepath.read_text()
        if yaml:
            return yaml.safe_load(text)
        raise ImportError("PyYAML is required. Install with: pip install pyyaml")
    except Exception:
        return None


# --- Rule loading ---


def load_rules(
    rules_dir: Path, lang_filter: str | None = None
) -> tuple[list[dict], list[str], int]:
    """Load approved rules, optionally filtered by language."""
    approved: list[dict] = []
    warnings: list[str] = []
    skipped = 0

    if not rules_dir.exists():
        return approved, ["Rules directory not found"], 0

    for yaml_file in sorted(rules_dir.rglob("*.yaml")):
        data = load_yaml_file(yaml_file)
        if not data:
            warnings.append(f"Failed to parse: {yaml_file}")
            continue

        source = data.get("source", {})
        dep_name = source.get("name", yaml_file.stem)
        language = _infer_language(yaml_file, source)

        if lang_filter and language != lang_filter:
            continue

        for rule in data.get("rules", []):
            if not rule.get("approved", False):
                skipped += 1
                continue
            rule["_language"] = language
            rule["_dep_name"] = dep_name
            approved.append(rule)

    return approved, warnings, skipped


def _infer_language(filepath: Path, source: dict) -> str:
    """Infer language from path or source."""
    path_str = str(filepath)
    if "/python/" in path_str:
        return "python"
    if "/typescript/" in path_str:
        return "typescript"
    if "/rust/" in path_str:
        return "rust"
    return source.get("language", "generic")


# --- Test file header ---


def _test_header(rule_id: str, source_url: str) -> str:
    """Generate a standard header comment."""
    return f"""# Rule: {rule_id}
# Source: {source_url}
# Generated by Whetstone — do not edit manually
"""


def _test_header_ts(rule_id: str, source_url: str, has_real_check: bool = False) -> str:
    # Supported signal types:
    #   Real checks: deprecated API detection (pattern), import checks (pattern),
    #                string literal checks (pattern)
    #   Partial:     async/sync detection (regex approximation)
    #   Unsupported: complex AST patterns (generates TODO scaffold)
    experimental = "" if has_real_check else (
        "// EXPERIMENTAL: TypeScript test generation produces signal scaffolds that\n"
        "// may require manual implementation for full enforcement. Review TODOs below.\n"
    )
    return f"""// Rule: {rule_id}
// Source: {source_url}
// Generated by Whetstone — do not edit manually
{experimental}"""


def _test_header_rs(rule_id: str, source_url: str, has_real_check: bool = False) -> str:
    # Supported signal types:
    #   Real checks: deprecated API detection (string contains), unsafe block detection,
    #                .unwrap() usage detection
    #   Partial:     import/use statement checks (string matching)
    #   Unsupported: complex AST patterns (generates TODO scaffold with Dylint reference)
    experimental = "" if has_real_check else (
        "// EXPERIMENTAL: Rust test generation produces signal scaffolds that\n"
        "// may require manual implementation for full enforcement. Review TODOs below.\n"
    )
    return f"""// Rule: {rule_id}
// Source: {source_url}
// Generated by Whetstone — do not edit manually
// For complex AST checks, consider using Dylint (https://github.com/trailofbits/dylint)
// to write custom lints that integrate with the Rust compiler.
{experimental}"""


# --- Python test generation ---


def _sanitize_name(name: str) -> str:
    """Convert a rule ID to a valid Python/Rust identifier."""
    return re.sub(r"[^a-zA-Z0-9]", "_", name).strip("_").lower()


def generate_python_test(rule: dict) -> str:
    """Generate a pytest test file for a Python rule."""
    rule_id = rule.get("id", "unknown")
    source_url = rule.get("source_url", "")
    description = rule.get("description", "").strip()
    dep_name = rule.get("_dep_name", "unknown")
    signals = rule.get("signals", [])

    header = _test_header(rule_id, source_url)
    func_name = _sanitize_name(rule_id)

    # Determine which imports we need based on signal strategies
    has_ast = any(s.get("strategy") == "ast" for s in signals)
    has_pattern = any(s.get("strategy") == "pattern" for s in signals)

    imports: list[str] = []
    if has_ast:
        imports.append("import ast")
    if has_pattern:
        imports.append("import re")
    imports.extend(["import glob", "import os", "from collections import defaultdict"])

    # Build signal checks
    checks: list[str] = []
    for signal in signals:
        strategy = signal.get("strategy", "")
        sig_desc = signal.get("description", "")
        sig_id = signal.get("id", "unknown")
        weight = signal.get("weight", "moderate")

        # Add signal identifier comment before each check
        checks.append(f"        # Signal: {sig_id} ({strategy}, {weight})")

        if strategy == "ast":
            checks.append(_generate_ast_check(sig_desc, dep_name))
        elif strategy == "pattern":
            checks.append(_generate_pattern_check(sig_desc))
        elif strategy == "lint_proxy":
            checks.append(f"        # Handled in linter config, not test")
            continue
        elif strategy == "ai":
            checks.append(f"        # AI signal (not auto-testable): {sig_desc}")

    if not checks:
        checks.append(f"        # TODO: Implement signal checks for: {description}")
        checks.append("        pass")

    check_body = "\n".join(checks)

    return f"""{header}
{chr(10).join(imports)}


def test_{func_name}():
    \"\"\"Check: {description}

    Source: {source_url}
    Rule ID: {rule_id}
    \"\"\"
    violations = []
    # Track violations per file for grouped output
    violations_by_file = defaultdict(list)

    for filepath in glob.glob('src/**/*.py', recursive=True):
        if 'whetstone/' in filepath:
            continue
        try:
            with open(filepath) as f:
                source = f.read()
        except (OSError, UnicodeDecodeError):
            continue

{check_body}

    # Group violations by file for clearer output
    grouped_msgs = []
    for fpath, msgs in violations_by_file.items():
        grouped_msgs.append(f"  {{fpath}}:")
        for msg in msgs:
            grouped_msgs.append(f"    - {{msg}}")

    assert not violations, (
        f"{{len(violations)}} violation(s) found for {rule_id}:\\n"
        + ("\\n".join(grouped_msgs) if grouped_msgs else "\\n".join(violations))
    )
"""


def _generate_ast_check(description: str, dep_name: str) -> str:
    """Generate an AST-based check from signal description."""
    desc_lower = description.lower()
    INDENT = "        "  # 8 spaces — inside the for loop

    # Common patterns: async vs sync functions
    if "async" in desc_lower and ("sync" in desc_lower or "def " in desc_lower):
        lines = [
            "# Check for sync route handlers that should be async",
            "try:",
            "    tree = ast.parse(source)",
            "except SyntaxError:",
            "    continue",
            "",
            "route_decorators = {'get', 'post', 'put', 'delete', 'patch', 'head', 'options'}",
            "for node in ast.walk(tree):",
            "    if isinstance(node, ast.FunctionDef) and not isinstance(node, ast.AsyncFunctionDef):",
            "        for decorator in node.decorator_list:",
            "            dec_name = ''",
            "            if isinstance(decorator, ast.Call):",
            "                if isinstance(decorator.func, ast.Attribute):",
            "                    dec_name = decorator.func.attr",
            "                elif isinstance(decorator.func, ast.Name):",
            "                    dec_name = decorator.func.id",
            "            elif isinstance(decorator, ast.Attribute):",
            "                dec_name = decorator.attr",
            "            elif isinstance(decorator, ast.Name):",
            "                dec_name = decorator.id",
            "            if dec_name in route_decorators:",
            '                violations.append(f"{filepath}:{node.lineno} - {node.name} is sync")',
            '                violations_by_file[filepath].append(f"line {node.lineno}: {node.name} is sync")',
        ]
        return "\n".join(INDENT + line if line else "" for line in lines)

    # Import-from check: "from X import Y" or "import X"
    if "import" in desc_lower and ("from" in desc_lower or "import" in desc_lower):
        return _generate_ast_check_import(description, dep_name)

    # Class inheritance check
    if "inherit" in desc_lower or "subclass" in desc_lower or "base class" in desc_lower:
        return _generate_ast_check_class(description, dep_name)

    # Keyword argument check
    if "keyword" in desc_lower or "kwarg" in desc_lower or "argument" in desc_lower:
        return _generate_ast_check_kwarg(description, dep_name)

    # Deprecated function call
    if "deprecated" in desc_lower or "instead of" in desc_lower:
        match = re.search(
            r"(?:uses?|calls?)\s+[`'\"]?(\w+(?:\.\w+)*)[`'\"]?", description
        )
        if match:
            old_name = match.group(1)
            short_name = old_name.split(".")[-1]
            lines = [
                f"# Check for deprecated call to {old_name}",
                "try:",
                "    tree = ast.parse(source)",
                "except SyntaxError:",
                "    continue",
                "",
                "for node in ast.walk(tree):",
                "    if isinstance(node, ast.Call):",
                "        call_name = ''",
                "        if isinstance(node.func, ast.Attribute):",
                "            call_name = node.func.attr",
                "        elif isinstance(node.func, ast.Name):",
                "            call_name = node.func.id",
                f"        if call_name == '{short_name}':",
                f'            violations.append(f"{{filepath}}:{{node.lineno}} - uses deprecated {old_name}")',
                f'            violations_by_file[filepath].append(f"line {{node.lineno}}: uses deprecated {old_name}")',
            ]
            return "\n".join(INDENT + line if line else "" for line in lines)

    # Default: generic AST walk with TODO
    lines = [
        "try:",
        "    tree = ast.parse(source)",
        "except SyntaxError:",
        "    continue",
        "",
        f"# TODO: Implement AST check for: {description}",
        "# Walk the AST and check for violations",
        "for node in ast.walk(tree):",
        "    pass  # Add specific checks here",
    ]
    return "\n".join(INDENT + line if line else "" for line in lines)


def _generate_ast_check_import(description: str, dep_name: str) -> str:
    """Generate an AST check for import statements (from X import Y / import X)."""
    INDENT = "        "

    # Try to extract module and name from description
    from_match = re.search(r"from\s+[`'\"]?(\w+(?:\.\w+)*)[`'\"]?\s+import\s+[`'\"]?(\w+)[`'\"]?", description)
    import_match = re.search(r"import\s+[`'\"]?(\w+(?:\.\w+)*)[`'\"]?", description)

    if from_match:
        module = from_match.group(1)
        name = from_match.group(2)
        lines = [
            f"# Check for 'from {module} import {name}' usage",
            "try:",
            "    tree = ast.parse(source)",
            "except SyntaxError:",
            "    continue",
            "",
            "for node in ast.walk(tree):",
            "    if isinstance(node, ast.ImportFrom):",
            f"        if node.module and '{module}' in node.module:",
            "            for alias in (node.names or []):",
            f"                if alias.name == '{name}':",
            f'                    violations.append(f"{{filepath}}:{{node.lineno}} - imports {name} from {module}")',
            f'                    violations_by_file[filepath].append(f"line {{node.lineno}}: imports {name} from {module}")',
        ]
    elif import_match:
        module = import_match.group(1)
        lines = [
            f"# Check for 'import {module}' usage",
            "try:",
            "    tree = ast.parse(source)",
            "except SyntaxError:",
            "    continue",
            "",
            "for node in ast.walk(tree):",
            "    # Check 'import X' statements",
            "    if isinstance(node, ast.Import):",
            "        for alias in node.names:",
            f"            if '{module}' in alias.name:",
            f'                violations.append(f"{{filepath}}:{{node.lineno}} - imports {module}")',
            f'                violations_by_file[filepath].append(f"line {{node.lineno}}: imports {module}")',
            "    # Check 'from X import ...' statements",
            "    elif isinstance(node, ast.ImportFrom):",
            f"        if node.module and '{module}' in node.module:",
            f'            violations.append(f"{{filepath}}:{{node.lineno}} - imports from {module}")',
            f'            violations_by_file[filepath].append(f"line {{node.lineno}}: imports from {module}")',
        ]
    else:
        lines = [
            "try:",
            "    tree = ast.parse(source)",
            "except SyntaxError:",
            "    continue",
            "",
            f"# TODO: Implement import check for: {description}",
            "for node in ast.walk(tree):",
            "    if isinstance(node, (ast.Import, ast.ImportFrom)):",
            "        pass  # Add specific import checks here",
        ]

    return "\n".join(INDENT + line if line else "" for line in lines)


def _generate_ast_check_class(description: str, dep_name: str) -> str:
    """Generate an AST check for class inheritance (class X inherits from Y)."""
    INDENT = "        "

    # Try to extract base class name from description
    base_match = re.search(r"(?:inherit|subclass|extend|derive)\w*\s+(?:from\s+)?[`'\"]?(\w+)[`'\"]?", description, re.IGNORECASE)
    base_name = base_match.group(1) if base_match else None

    if base_name:
        lines = [
            f"# Check for classes that inherit from {base_name}",
            "try:",
            "    tree = ast.parse(source)",
            "except SyntaxError:",
            "    continue",
            "",
            "for node in ast.walk(tree):",
            "    if isinstance(node, ast.ClassDef):",
            "        for base in node.bases:",
            "            base_id = ''",
            "            if isinstance(base, ast.Name):",
            "                base_id = base.id",
            "            elif isinstance(base, ast.Attribute):",
            "                base_id = base.attr",
            f"            if base_id == '{base_name}':",
            f'                violations.append(f"{{filepath}}:{{node.lineno}} - class {{node.name}} inherits from {base_name}")',
            f'                violations_by_file[filepath].append(f"line {{node.lineno}}: class {{node.name}} inherits from {base_name}")',
        ]
    else:
        lines = [
            "try:",
            "    tree = ast.parse(source)",
            "except SyntaxError:",
            "    continue",
            "",
            f"# TODO: Implement class inheritance check for: {description}",
            "for node in ast.walk(tree):",
            "    if isinstance(node, ast.ClassDef):",
            "        pass  # Check node.bases for specific base classes",
        ]

    return "\n".join(INDENT + line if line else "" for line in lines)


def _generate_ast_check_kwarg(description: str, dep_name: str) -> str:
    """Generate an AST check for keyword arguments in function calls."""
    INDENT = "        "

    # Try to extract function and kwarg names from description
    func_match = re.search(r"[`'\"]?(\w+(?:\.\w+)*)\(\)[`'\"]?", description)
    kwarg_match = re.search(r"(?:keyword|kwarg|argument)\s+[`'\"]?(\w+)[`'\"]?", description, re.IGNORECASE)

    func_name = func_match.group(1).split(".")[-1] if func_match else None
    kwarg_name = kwarg_match.group(1) if kwarg_match else None

    if func_name and kwarg_name:
        lines = [
            f"# Check that calls to {func_name}() include the '{kwarg_name}' keyword argument",
            "try:",
            "    tree = ast.parse(source)",
            "except SyntaxError:",
            "    continue",
            "",
            "for node in ast.walk(tree):",
            "    if isinstance(node, ast.Call):",
            "        call_name = ''",
            "        if isinstance(node.func, ast.Attribute):",
            "            call_name = node.func.attr",
            "        elif isinstance(node.func, ast.Name):",
            "            call_name = node.func.id",
            f"        if call_name == '{func_name}':",
            f"            kwarg_names = [kw.arg for kw in node.keywords if kw.arg]",
            f"            if '{kwarg_name}' not in kwarg_names:",
            f'                violations.append(f"{{filepath}}:{{node.lineno}} - {func_name}() called without {kwarg_name} kwarg")',
            f'                violations_by_file[filepath].append(f"line {{node.lineno}}: {func_name}() called without {kwarg_name} kwarg")',
        ]
    else:
        lines = [
            "try:",
            "    tree = ast.parse(source)",
            "except SyntaxError:",
            "    continue",
            "",
            f"# TODO: Implement keyword argument check for: {description}",
            "for node in ast.walk(tree):",
            "    if isinstance(node, ast.Call):",
            "        pass  # Check node.keywords for specific kwargs",
        ]

    return "\n".join(INDENT + line if line else "" for line in lines)


def _generate_pattern_check(description: str) -> str:
    """Generate a regex-based check from signal description."""
    desc_lower = description.lower()
    INDENT = "        "  # 8 spaces — inside the for loop

    # Try to extract a pattern to search for
    if (
        "deprecated" in desc_lower
        or ".schema()" in description
        or "calls" in desc_lower
    ):
        match = re.search(r"\.(\w+\(\))", description)
        if not match:
            match = re.search(r"[`'\"](\w+(?:\.\w+)*)[`'\"]", description)
        if match:
            raw = match.group(1)
            pattern = re.escape(raw)
            lines = [
                "for i, line in enumerate(source.splitlines(), 1):",
                f"    if re.search(r'{pattern}', line):",
                f'        violations.append(f"{{filepath}}:{{i}} - matches deprecated pattern: {raw}")',
            ]
            return "\n".join(INDENT + line for line in lines)

    # Default: generic pattern check with TODO
    lines = [
        f"# TODO: Implement pattern check for: {description}",
        "# Example:",
        "# for i, line in enumerate(source.splitlines(), 1):",
        "#     if re.search(r'pattern_here', line):",
        '#         violations.append(f"{filepath}:{i} - violation description")',
    ]
    return "\n".join(INDENT + line for line in lines)


def generate_python_conftest(output_dir: Path) -> str:
    """Generate conftest.py with shared fixtures."""
    return """# Generated by Whetstone — do not edit manually
# Shared pytest fixtures for Whetstone eval tests

import pytest
import os


@pytest.fixture
def project_python_files():
    \"\"\"Collect all Python files in src/ for analysis.\"\"\"
    files = []
    for root, dirs, filenames in os.walk('src'):
        # Skip whetstone directory
        dirs[:] = [d for d in dirs if d != 'whetstone']
        for filename in filenames:
            if filename.endswith('.py'):
                files.append(os.path.join(root, filename))
    return files
"""


# --- TypeScript test generation ---


def _generate_ts_pattern_import_check(sig_desc: str) -> str:
    """Generate a TypeScript import check from a signal description."""
    # Try to extract 'from X import Y' or 'import X' pattern
    from_match = re.search(r"(?:from|import)\s+[`'\"]?(\w+(?:[/.]\w+)*)[`'\"]?", sig_desc)
    if from_match:
        module = from_match.group(1)
        escaped = module.replace("/", "\\\\/").replace(".", "\\\\.")
        return textwrap.dedent(f"""\
      // Check for import of {module}
      for (let i = 0; i < lines.length; i++) {{
        if (/(?:import\\s.*from\\s+['\"]|require\\().*{escaped}/.test(lines[i])) {{
          violations.push(`${{filepath}}:${{i + 1}} - imports {module}`);
        }}
      }}""")
    return ""


def _generate_ts_signal_check(signal: dict, dep_name: str) -> str:
    """Generate a TypeScript signal check from a signal definition."""
    strategy = signal.get("strategy", "")
    sig_desc = signal.get("description", "")
    sig_id = signal.get("id", "unknown")
    weight = signal.get("weight", "moderate")
    desc_lower = sig_desc.lower()

    # Add signal identifier comment
    prefix = f"      // Signal: {sig_id} ({strategy}, {weight})\n"

    if strategy == "ai":
        return f"{prefix}      // AI signal (not auto-testable): {sig_desc}"

    if strategy == "lint_proxy":
        return f"{prefix}      // lint_proxy signal (handled by biome config): {sig_desc}"

    # Pattern-based checks
    if strategy == "pattern":
        # Import check
        if "import" in desc_lower:
            import_check = _generate_ts_pattern_import_check(sig_desc)
            if import_check:
                return prefix + import_check

        # Try to extract a deprecated function/method name
        deprecated_match = re.search(
            r"(?:uses?|calls?|invokes?)\s+[`'\"]?(\w+(?:\.\w+)*(?:\(\))?)[`'\"]?",
            sig_desc,
        )
        if deprecated_match or "deprecated" in desc_lower:
            target = deprecated_match.group(1) if deprecated_match else ""
            if target:
                escaped = target.replace("(", "\\\\(").replace(")", "\\\\)")
                return prefix + textwrap.dedent(f"""\
      for (let i = 0; i < lines.length; i++) {{
        if (/{escaped}/.test(lines[i])) {{
          violations.push(`${{filepath}}:${{i + 1}} - uses deprecated {target}`);
        }}
      }}""")

        # Generic pattern: try to extract a regex-worthy token
        token_match = re.search(r"[`'\"]([^`'\"]+)[`'\"]", sig_desc)
        if token_match:
            token = token_match.group(1).replace("(", "\\\\(").replace(")", "\\\\)")
            return prefix + textwrap.dedent(f"""\
      for (let i = 0; i < lines.length; i++) {{
        if (/{token}/.test(lines[i])) {{
          violations.push(`${{filepath}}:${{i + 1}} - matches pattern: {token_match.group(1)}`);
        }}
      }}""")

    # AST-based checks — generate regex approximations since we can't use a real TS parser
    if strategy == "ast":
        # Async vs sync function detection
        if "async" in desc_lower and (
            "sync" in desc_lower or "def " in desc_lower or "function" in desc_lower
        ):
            return prefix + textwrap.dedent("""\
      // Check for sync route handlers that should be async (regex approximation)
      const routeDecorators = /(?:@(?:Get|Post|Put|Delete|Patch)\\(|app\\.(?:get|post|put|delete|patch)\\()/;
      for (let i = 0; i < lines.length; i++) {
        if (routeDecorators.test(lines[i]) || (i > 0 && routeDecorators.test(lines[i - 1]))) {
          // Check if the next non-empty line is a sync function
          for (let j = i; j < Math.min(i + 3, lines.length); j++) {
            if (/^\\s*(?:export\\s+)?function\\s/.test(lines[j]) && !/async\\s+function/.test(lines[j])) {
              violations.push(`${filepath}:${j + 1} - sync function used as route handler`);
            }
          }
        }
      }""")

        # Deprecated function call
        deprecated_match = re.search(
            r"(?:uses?|calls?)\s+[`'\"]?(\w+(?:\.\w+)*)[`'\"]?", sig_desc
        )
        if deprecated_match or "deprecated" in desc_lower:
            target = deprecated_match.group(1) if deprecated_match else ""
            if target:
                short = target.split(".")[-1]
                return prefix + textwrap.dedent(f"""\
      for (let i = 0; i < lines.length; i++) {{
        if (/\\b{short}\\b/.test(lines[i])) {{
          violations.push(`${{filepath}}:${{i + 1}} - uses deprecated {target}`);
        }}
      }}""")

    # Fallback: signal comment with TODO
    return f"{prefix}      // TODO: Implement {strategy} check for: {sig_desc}"


def generate_typescript_test(rule: dict) -> str:
    """Generate a vitest test file for a TypeScript rule."""
    rule_id = rule.get("id", "unknown")
    source_url = rule.get("source_url", "")
    description = rule.get("description", "").strip()
    dep_name = rule.get("_dep_name", "unknown")
    signals = rule.get("signals", [])

    # Build signal checks first to determine if we have real checks
    signal_checks: list[str] = []
    has_real_check = False
    for signal in signals:
        check = _generate_ts_signal_check(signal, dep_name)
        signal_checks.append(check)
        if (
            "TODO" not in check
            and "AI signal" not in check
            and "lint_proxy" not in check
        ):
            has_real_check = True

    # Only show EXPERIMENTAL header when all signals are TODO scaffolds
    header = _test_header_ts(rule_id, source_url, has_real_check=has_real_check)

    checks = (
        "\n\n".join(signal_checks)
        if signal_checks
        else "      // TODO: Implement signal checks"
    )

    # If we have at least one real check, remove the generic TODO footer
    todo_footer = (
        ""
        if has_real_check
        else "\n      // TODO: Add file scanning logic based on signals above"
    )

    return f"""{header}
import {{ describe, it, expect }} from 'vitest';
import * as fs from 'fs';
import * as path from 'path';
import {{ globSync }} from 'glob';

describe('{rule_id}', () => {{
  /**
   * {description}
   * Source: {source_url}
   */
  it('{description.replace(chr(39), chr(92) + chr(39))}', () => {{
    const violations: string[] = [];
    const files = globSync('src/**/*.{{ts,tsx}}');

    for (const filepath of files) {{
      if (filepath.includes('whetstone/')) continue;
      const content = fs.readFileSync(filepath, 'utf-8');
      const lines = content.split('\\n');

{checks}{todo_footer}
    }}

    expect(violations).toEqual([]);
  }});
}});
"""


def generate_typescript_setup() -> str:
    """Generate a setup.ts file with shared test utilities for TypeScript rules."""
    return textwrap.dedent("""\
    // Generated by Whetstone — do not edit manually
    // Shared test utilities for Whetstone TypeScript eval tests

    import * as fs from 'fs';
    import * as path from 'path';
    import { globSync } from 'glob';

    /**
     * Discover all TypeScript files in the project source directory.
     * Excludes whetstone-generated files and node_modules.
     */
    export function findSourceFiles(
      baseDir: string = 'src',
      extensions: string[] = ['ts', 'tsx']
    ): string[] {
      const pattern = `${baseDir}/**/*.{${extensions.join(',')}}`;
      return globSync(pattern).filter(
        (f: string) => !f.includes('whetstone/') && !f.includes('node_modules/')
      );
    }

    /**
     * Read a file and split into lines for line-by-line analysis.
     */
    export function readLines(filepath: string): string[] {
      try {
        return fs.readFileSync(filepath, 'utf-8').split('\\n');
      } catch {
        return [];
      }
    }

    /**
     * Format a violation message with file path and line number.
     */
    export function violation(filepath: string, line: number, message: string): string {
      return `${filepath}:${line} - ${message}`;
    }
    """)



# --- Rust test generation ---


def _generate_rs_use_check(sig_desc: str, indent: str) -> str:
    """Generate a Rust use statement check from a signal description."""
    use_match = re.search(r"use\s+[`'\"]?(\w+(?:::\w+)*)[`'\"]?", sig_desc)
    if use_match:
        path = use_match.group(1)
        return textwrap.dedent(f"""\
{indent}// Check for 'use {path}' statement
{indent}for (i, line) in content.lines().enumerate() {{
{indent}    let trimmed = line.trim();
{indent}    if trimmed.starts_with("use ") && trimmed.contains("{path}") {{
{indent}        violations.push(format!(
{indent}            "{{}}:{{}} - uses {path}",
{indent}            filepath, i + 1
{indent}        ));
{indent}    }}
{indent}}}""")
    return ""


def _generate_rs_signal_check(signal: dict, dep_name: str) -> str:
    """Generate a Rust signal check from a signal definition."""
    strategy = signal.get("strategy", "")
    sig_desc = signal.get("description", "")
    sig_id = signal.get("id", "unknown")
    weight = signal.get("weight", "moderate")
    desc_lower = sig_desc.lower()
    INDENT = "            "  # 12 spaces — inside for loop body

    # Add signal identifier comment
    prefix = f"{INDENT}// Signal: {sig_id} ({strategy}, {weight})\n"

    if strategy == "ai":
        return f"{prefix}{INDENT}// AI signal (not auto-testable): {sig_desc}"

    if strategy == "lint_proxy":
        return f"{prefix}{INDENT}// lint_proxy signal (handled by clippy config): {sig_desc}"

    # Pattern-based checks
    if strategy == "pattern":
        # Use statement check
        if "use " in desc_lower or "use::" in sig_desc:
            use_check = _generate_rs_use_check(sig_desc, INDENT)
            if use_check:
                return prefix + use_check

        # Try to extract a deprecated function/method name
        deprecated_match = re.search(
            r"(?:uses?|calls?|invokes?)\s+[`'\"]?(\w+(?:::\w+)*(?:\(\))?)[`'\"]?",
            sig_desc,
        )
        if deprecated_match or "deprecated" in desc_lower:
            target = deprecated_match.group(1) if deprecated_match else ""
            if target:
                return prefix + textwrap.dedent(f"""\
{INDENT}for (i, line) in content.lines().enumerate() {{
{INDENT}    if line.contains("{target}") {{
{INDENT}        violations.push(format!(
{INDENT}            "{{}}:{{}} - uses deprecated {target}",
{INDENT}            filepath, i + 1
{INDENT}        ));
{INDENT}    }}
{INDENT}}}""")

        # Generic pattern: try to extract a token
        token_match = re.search(r"[`'\"]([^`'\"]+)[`'\"]", sig_desc)
        if token_match:
            token = token_match.group(1)
            return prefix + textwrap.dedent(f"""\
{INDENT}for (i, line) in content.lines().enumerate() {{
{INDENT}    if line.contains("{token}") {{
{INDENT}        violations.push(format!(
{INDENT}            "{{}}:{{}} - matches pattern: {token}",
{INDENT}            filepath, i + 1
{INDENT}        ));
{INDENT}    }}
{INDENT}}}""")

    # AST-based checks — generate string matching approximations
    if strategy == "ast":
        # Use statement check (also valid in ast strategy)
        if "use " in desc_lower or "use::" in sig_desc:
            use_check = _generate_rs_use_check(sig_desc, INDENT)
            if use_check:
                return prefix + use_check

        # Unsafe block detection
        if "unsafe" in desc_lower:
            return prefix + textwrap.dedent(f"""\
{INDENT}for (i, line) in content.lines().enumerate() {{
{INDENT}    let trimmed = line.trim();
{INDENT}    if trimmed.starts_with("unsafe ") || trimmed.contains("unsafe {{") {{
{INDENT}        violations.push(format!(
{INDENT}            "{{}}:{{}} - uses unsafe block",
{INDENT}            filepath, i + 1
{INDENT}        ));
{INDENT}    }}
{INDENT}}}""")

        # Unwrap detection
        if "unwrap" in desc_lower or "panic" in desc_lower:
            return prefix + textwrap.dedent(f"""\
{INDENT}for (i, line) in content.lines().enumerate() {{
{INDENT}    if line.contains(".unwrap()") && !line.trim().starts_with("//") {{
{INDENT}        violations.push(format!(
{INDENT}            "{{}}:{{}} - uses .unwrap() which may panic",
{INDENT}            filepath, i + 1
{INDENT}        ));
{INDENT}    }}
{INDENT}}}""")

        # Deprecated function call
        deprecated_match = re.search(
            r"(?:uses?|calls?)\s+[`'\"]?(\w+(?:::\w+)*)[`'\"]?", sig_desc
        )
        if deprecated_match or "deprecated" in desc_lower:
            target = deprecated_match.group(1) if deprecated_match else ""
            if target:
                short = target.split("::")[-1]
                return prefix + textwrap.dedent(f"""\
{INDENT}for (i, line) in content.lines().enumerate() {{
{INDENT}    if line.contains("{short}") && !line.trim().starts_with("//") {{
{INDENT}        violations.push(format!(
{INDENT}            "{{}}:{{}} - uses deprecated {target}",
{INDENT}            filepath, i + 1
{INDENT}        ));
{INDENT}    }}
{INDENT}}}""")

    # Fallback — for complex AST checks, suggest Dylint
    return f"{prefix}{INDENT}// TODO: Implement {strategy} check for: {sig_desc}\n{INDENT}// For complex AST analysis in Rust, consider Dylint: https://github.com/trailofbits/dylint"


def generate_rust_test(rule: dict) -> str:
    """Generate a cargo test file for a Rust rule."""
    rule_id = rule.get("id", "unknown")
    source_url = rule.get("source_url", "")
    dep_name = rule.get("_dep_name", "unknown")
    description = rule.get("description", "").strip()
    func_name = _sanitize_name(rule_id)
    signals = rule.get("signals", [])

    # Build signal checks first to determine if we have real checks
    signal_checks: list[str] = []
    has_real_check = False
    for signal in signals:
        check = _generate_rs_signal_check(signal, dep_name)
        signal_checks.append(check)
        if (
            "TODO" not in check
            and "AI signal" not in check
            and "lint_proxy" not in check
        ):
            has_real_check = True

    header = _test_header_rs(rule_id, source_url, has_real_check=has_real_check)

    checks = (
        "\n\n".join(signal_checks)
        if signal_checks
        else "            // TODO: Implement signal checks"
    )
    todo_footer = (
        ""
        if has_real_check
        else "\n\n            // TODO: Add content scanning logic based on signals above"
    )

    return f"""{header}

#[cfg(test)]
mod {func_name}_tests {{
    use std::fs;
    use std::path::Path;

    fn find_rs_files(dir: &str) -> Vec<String> {{
        let mut files = Vec::new();
        if let Ok(entries) = fs::read_dir(dir) {{
            for entry in entries.flatten() {{
                let path = entry.path();
                if path.is_dir() && !path.to_str().unwrap_or("").contains("whetstone") {{
                    files.extend(find_rs_files(path.to_str().unwrap_or("")));
                }} else if path.extension().map_or(false, |e| e == "rs") {{
                    if let Some(p) = path.to_str() {{
                        files.push(p.to_string());
                    }}
                }}
            }}
        }}
        files
    }}

    #[test]
    fn test_{func_name}() {{
        let mut violations: Vec<String> = Vec::new();
        let files = find_rs_files("src");

        for filepath in &files {{
            let content = match fs::read_to_string(filepath) {{
                Ok(c) => c,
                Err(_) => continue,
            }};

{checks}{todo_footer}
        }}

        assert!(
            violations.is_empty(),
            "{{}} violation(s) found for {rule_id}:\\n{{}}",
            violations.len(),
            violations.join("\\n")
        );
    }}
}}
"""


# --- Linter config generation ---


def generate_ruff_config(rules: list[dict]) -> str:
    """Generate ruff.whetstone.toml overlay."""
    lines = [
        "# Generated by Whetstone — do not edit manually",
        "# Ruff configuration overlay for Whetstone rules",
        f"# Last updated: {datetime.now(timezone.utc).strftime('%Y-%m-%d')}",
        "",
        "[lint]",
    ]

    select_rules: list[str] = []
    for rule in rules:
        for signal in rule.get("signals", []):
            if signal.get("strategy") == "lint_proxy":
                # Try to extract ruff rule code from description
                desc = signal.get("description", "")
                match = re.search(r"\b([A-Z]+\d{3,4})\b", desc)
                if match:
                    select_rules.append(match.group(1))

    if select_rules:
        rules_str = ", ".join(f'"{r}"' for r in sorted(set(select_rules)))
        lines.append(f"extend-select = [{rules_str}]")
    else:
        lines.append("# No lint_proxy signals found in rules")
        lines.append("# extend-select = []")

    lines.append("")
    return "\n".join(lines)


def _categorize_biome_rule(rule_name: str) -> str:
    """Categorize a biome rule into its group (suspicious, correctness, style, etc.)."""
    # Rules starting with 'no' that indicate suspicious code
    suspicious_rules = {
        "noExplicitAny", "noDebugger", "noConsoleLog", "noDoubleEquals",
        "noShadowRestrictedNames", "noImplicitAnyLet", "noArrayIndexKey",
        "noAssignInExpressions", "noConfusingVoidType",
    }
    # Rules about correctness
    correctness_rules = {
        "noUnusedVariables", "noUnusedImports", "noUndeclaredVariables",
        "noInvalidConstructorSuper", "noConstAssign", "noEmptyPattern",
        "noNewSymbol", "noUnsafeFinally", "noVoidTypeReturn",
        "noChildrenProp", "noRenderReturnValue",
    }
    # Rules about style
    style_rules = {
        "useConst", "useTemplate", "useSelfClosingElements",
        "useImportType", "useEnumInitializers", "useExponentiationOperator",
        "useNumericLiterals", "useSingleVarDeclarator",
    }
    if rule_name in suspicious_rules:
        return "suspicious"
    if rule_name in correctness_rules:
        return "correctness"
    if rule_name in style_rules:
        return "style"
    # Default: suspicious for 'no' rules, style for 'use' rules
    if rule_name.startswith("no"):
        return "suspicious"
    if rule_name.startswith("use"):
        return "style"
    return "suspicious"


def generate_biome_config(rules: list[dict]) -> dict:
    """Generate biome.whetstone.json overlay with proper nested group structure."""
    # Collect rules by biome group
    grouped: dict[str, dict[str, str]] = {}

    for rule in rules:
        for signal in rule.get("signals", []):
            if signal.get("strategy") == "lint_proxy":
                desc = signal.get("description", "")
                # Try to extract biome rule name
                match = re.search(r"\b(no\w+|use\w+)\b", desc)
                if match:
                    rule_name = match.group(1)
                    group = _categorize_biome_rule(rule_name)
                    if group not in grouped:
                        grouped[group] = {}
                    grouped[group][rule_name] = "error"

    config: dict = {
        "$schema": "https://biomejs.dev/schemas/1.9.4/schema.json",
        "_comment": "Generated by Whetstone — do not edit manually",
        "linter": {
            "enabled": True,
            "rules": grouped if grouped else {},
        },
    }

    return config


def _categorize_clippy_lint(lint_name: str) -> str:
    """Categorize a clippy lint into its group (Pedantic, Correctness, Restriction, etc.)."""
    # Well-known pedantic lints
    pedantic_lints = {
        "doc_markdown", "missing_errors_doc", "missing_panics_doc",
        "must_use_candidate", "module_name_repetitions", "redundant_closure_for_method_calls",
        "needless_pass_by_value", "trivially_copy_pass_by_ref", "too_many_lines",
    }
    # Well-known correctness lints
    correctness_lints = {
        "absurd_extreme_comparisons", "erasing_op", "almost_swapped",
        "approx_constant", "deprecated_cfg_attr", "misrefactored_assign_op",
    }
    # Well-known restriction lints
    restriction_lints = {
        "unwrap_used", "expect_used", "print_stdout", "print_stderr",
        "dbg_macro", "todo", "unimplemented", "panic", "unreachable",
        "indexing_slicing", "as_conversions", "shadow_reuse",
    }
    if lint_name in pedantic_lints:
        return "Pedantic"
    if lint_name in correctness_lints:
        return "Correctness"
    if lint_name in restriction_lints:
        return "Restriction"
    return "Style"


def generate_clippy_config(rules: list[dict]) -> str:
    """Generate clippy.whetstone.toml overlay with lint categories."""
    lines = [
        "# Generated by Whetstone — do not edit manually",
        "# Clippy configuration overlay for Whetstone rules",
        f"# Last updated: {datetime.now(timezone.utc).strftime('%Y-%m-%d')}",
        "",
        "[lints.clippy]",
    ]

    # Collect lints grouped by category
    categorized: dict[str, list[tuple[str, str]]] = {}

    for rule in rules:
        for signal in rule.get("signals", []):
            if signal.get("strategy") == "lint_proxy":
                desc = signal.get("description", "")
                # Try to extract clippy lint names (snake_case identifiers)
                match = re.search(r"\b([a-z][a-z0-9_]+)\b", desc)
                if match:
                    lint_name = match.group(1)
                    # Determine severity: 'deny' for restriction/correctness, 'warn' for pedantic/style
                    category = _categorize_clippy_lint(lint_name)
                    if category in ("Restriction", "Correctness"):
                        level = "deny"
                    else:
                        level = "warn"
                    if category not in categorized:
                        categorized[category] = []
                    categorized[category].append((lint_name, level))

    if categorized:
        for category in sorted(categorized.keys()):
            lines.append(f"# {category}")
            for lint_name, level in sorted(categorized[category]):
                lines.append(f'{lint_name} = "{level}"')
        lines.append("")
    else:
        lines.append("# No lint_proxy signals found in rules")
        lines.append("")

    return "\n".join(lines)


# --- Main orchestration ---


def generate_tests(
    project_dir: Path,
    rules_dir: Path | None = None,
    output_dir: Path | None = None,
    lint_dir: Path | None = None,
    lang_filter: str | None = None,
    dry_run: bool = False,
) -> dict:
    """Main test generation logic."""
    if rules_dir is None:
        rules_dir = project_dir / "whetstone" / "rules"
    if output_dir is None:
        output_dir = project_dir / "whetstone" / "evals"
    if lint_dir is None:
        lint_dir = project_dir / "whetstone" / "lint"

    rules, warnings, skipped = load_rules(rules_dir, lang_filter)

    if not rules:
        return {
            "generated": {
                "tests": {"python": [], "typescript": [], "rust": []},
                "lint_configs": [],
            },
            "rules_processed": 0,
            "skipped_unapproved": skipped,
            "warnings": warnings or ["No approved rules found"],
            "next_command": "Extract rules first: run whetstone doctor",
        }

    # Group by language
    by_lang: dict[str, list[dict]] = {"python": [], "typescript": [], "rust": []}
    for rule in rules:
        lang = rule.get("_language", "")
        if lang in by_lang:
            by_lang[lang].append(rule)

    generated_tests: dict[str, list[str]] = {"python": [], "typescript": [], "rust": []}
    generated_lint: list[str] = []

    # --- Python ---
    if by_lang["python"]:
        py_dir = output_dir / "python"
        if not dry_run:
            py_dir.mkdir(parents=True, exist_ok=True)

        for rule in by_lang["python"]:
            rule_id = rule.get("id", "unknown")
            fname = f"test_{_sanitize_name(rule_id)}.py"
            fpath = py_dir / fname

            content = generate_python_test(rule)
            if not dry_run:
                fpath.write_text(content)
            generated_tests["python"].append(str(fpath))

        # conftest.py
        conftest_path = py_dir / "conftest.py"
        if not dry_run:
            conftest_path.write_text(generate_python_conftest(py_dir))

        # Ruff config
        if not dry_run:
            lint_dir.mkdir(parents=True, exist_ok=True)
        ruff_path = lint_dir / "ruff.whetstone.toml"
        ruff_content = generate_ruff_config(by_lang["python"])
        if not dry_run:
            ruff_path.write_text(ruff_content)
        generated_lint.append(str(ruff_path))

    # --- TypeScript ---
    if by_lang["typescript"]:
        print(
            "  [experimental] TypeScript test generation produces signal scaffolds "
            "that may need manual implementation.",
            file=sys.stderr,
        )
        ts_dir = output_dir / "typescript"
        if not dry_run:
            ts_dir.mkdir(parents=True, exist_ok=True)

        for rule in by_lang["typescript"]:
            rule_id = rule.get("id", "unknown")
            fname = f"{rule_id.replace('.', '-')}.test.ts"
            fpath = ts_dir / fname

            content = generate_typescript_test(rule)
            if not dry_run:
                fpath.write_text(content)
            generated_tests["typescript"].append(str(fpath))

        # Generate setup.ts with shared test utilities
        setup_path = ts_dir / "setup.ts"
        if not dry_run:
            setup_path.write_text(generate_typescript_setup())

        # Biome config
        if not dry_run:
            lint_dir.mkdir(parents=True, exist_ok=True)
        biome_path = lint_dir / "biome.whetstone.json"
        biome_config = generate_biome_config(by_lang["typescript"])
        if not dry_run:
            biome_path.write_text(json.dumps(biome_config, indent=2) + "\n")
        generated_lint.append(str(biome_path))

    # --- Rust ---
    if by_lang["rust"]:
        print(
            "  [experimental] Rust test generation produces signal scaffolds "
            "that may need manual implementation.",
            file=sys.stderr,
        )
        rs_dir = output_dir / "rust"
        if not dry_run:
            rs_dir.mkdir(parents=True, exist_ok=True)

        for rule in by_lang["rust"]:
            rule_id = rule.get("id", "unknown")
            fname = f"whetstone_{_sanitize_name(rule_id)}.rs"
            fpath = rs_dir / fname

            content = generate_rust_test(rule)
            if not dry_run:
                fpath.write_text(content)
            generated_tests["rust"].append(str(fpath))

        # Clippy config
        if not dry_run:
            lint_dir.mkdir(parents=True, exist_ok=True)
        clippy_path = lint_dir / "clippy.whetstone.toml"
        clippy_content = generate_clippy_config(by_lang["rust"])
        if not dry_run:
            clippy_path.write_text(clippy_content)
        generated_lint.append(str(clippy_path))

    # Build appropriate next command based on what was generated
    test_paths = []
    if "python" in by_lang:
        test_paths.append("pytest whetstone/evals/python/")
    if "typescript" in by_lang:
        test_paths.append("npx vitest run whetstone/evals/typescript/")
    if "rust" in by_lang:
        test_paths.append("cargo test --test whetstone")

    if test_paths:
        next_command = "Run tests: " + " && ".join(test_paths)
    else:
        next_command = "Check status: python3 scripts/status.py --project-dir ."

    result: dict = {
        "generated": {
            "tests": generated_tests,
            "lint_configs": generated_lint,
        },
        "rules_processed": len(rules),
        "skipped_unapproved": skipped,
        "next_command": next_command,
    }
    if warnings:
        result["warnings"] = warnings

    return result


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate test files and linter configs from approved Whetstone rules."
    )
    parser.add_argument(
        "--project-dir",
        type=Path,
        default=Path("."),
        help="Project root directory (default: .)",
    )
    parser.add_argument(
        "--rules-dir",
        type=Path,
        help="Rules directory (default: whetstone/rules)",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        help="Test output directory (default: whetstone/evals)",
    )
    parser.add_argument(
        "--lint-dir",
        type=Path,
        help="Lint config output directory (default: whetstone/lint)",
    )
    parser.add_argument(
        "--lang",
        choices=["python", "typescript", "rust"],
        help="Only generate for specified language",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be generated without writing files",
    )
    args = parser.parse_args()

    try:
        result = generate_tests(
            project_dir=args.project_dir,
            rules_dir=args.rules_dir,
            output_dir=args.output_dir,
            lint_dir=args.lint_dir,
            lang_filter=args.lang,
            dry_run=args.dry_run,
        )

        json.dump(result, sys.stdout, indent=2)
        sys.stdout.write("\n")

    except Exception as e:
        json.dump(
            {
                "error": str(e),
                "next_command": "Check rules directory and PyYAML installation",
            },
            sys.stdout,
            indent=2,
        )
        sys.stdout.write("\n")
        sys.exit(1)


if __name__ == "__main__":
    main()
