#!/usr/bin/env python3
"""Rebuild index.html: the product's dashboard assets plus the demo backend.

Run from anywhere: python3 planning/direction-demo/build.py
It reads assets/dashboard/ and mock.js and writes index.html beside itself.
"""

from pathlib import Path

HERE = Path(__file__).resolve().parent
ASSETS = HERE.parent.parent / "assets" / "dashboard"

DEMO_CSS = (
    ".demo{display:flex;flex-wrap:wrap;gap:.25rem 1rem;align-items:center;"
    "padding:.35rem 1.25rem;font-size:12.5px;color:var(--ghost)}"
    ".demo b{font-weight:500;color:var(--muted-foreground)}"
    ".demo label{display:inline-flex;gap:.35rem;align-items:center;cursor:pointer}"
    ".demo input{width:auto;margin:0;accent-color:var(--primary)}"
    ".demo code{font-size:12px}.demo .btn{font-size:12.5px;padding:.1rem .45rem}"
)
DEMO_STRIP = (
    '<div class=demo aria-label="Demo controls"><b>Demo controls</b>'
    "<span>Not part of the product. Sample data is fictional.</span>"
    "<label><input type=radio name=demo value=fresh> Fresh project "
    "(before <code>wh init</code>)</label>"
    "<label><input type=radio name=demo value=established> Established project</label>"
    '<button class="btn quiet" id=demo-reset type=button>Reset sample data</button></div>'
)
# The lazy modules load from inline text through blob URLs instead of the
# server paths wh dash serves.
LOADER = (
    'const DEMO={};for(const n of ["views","edit"])DEMO[n]=URL.createObjectURL('
    'new Blob([document.getElementById("src-"+n).textContent],{type:"text/javascript"}));'
)


def replace_once(text, old, new):
    assert text.count(old) == 1, f"expected one {old!r} in the dashboard assets"
    return text.replace(old, new)


def main():
    read = lambda name: (ASSETS / name).read_text()  # noqa: E731
    index, app, views, edit = (
        read(n) for n in ("index.html", "app.js", "views.js", "edit.js")
    )
    app = replace_once(
        app,
        'const l=h("link",{rel:"stylesheet",href:"/views.css"});d.head.append(l);'
        'await new Promise(r=>{l.onload=r;l.onerror=r});W.views=await import("/views.js")',
        "W.views=await import(DEMO.views)",
    )
    app = replace_once(app, 'import("/edit.js")', "import(DEMO.edit)")
    app = replace_once(app, '"wh dash · "+location.host', '"wh dash · 127.0.0.1:62772"')
    assert "</script" not in views and "</script" not in edit
    body = index[index.index("<a class=skip") :]
    body = replace_once(body, "Skip to content</a>", "Skip to content</a>" + DEMO_STRIP)
    page = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="color-scheme" content="light dark">
<title>Whetstone dashboard reference</title>
<!-- Direction reference for wh dash (Beads whetstone-ppq.1.3), generated by
     build.py: the product's own dashboard assets from assets/dashboard/ with
     the in-page demo backend in mock.js and fictional data. No network, no
     server. Edit mock.js or the assets, then rerun build.py. -->
<style>
{read("app.css")}
{read("views.css")}
{DEMO_CSS}
</style>
<script type="text/plain" id="src-views">{views}</script>
<script type="text/plain" id="src-edit">{edit}</script>
<script>
{(HERE / "mock.js").read_text()}
</script>
<script>
{LOADER}
{app}
</script>
</head>
<body>
{body}
</body>
</html>
"""
    (HERE / "index.html").write_text(page)
    print(f"wrote index.html ({len(page)} bytes)")


if __name__ == "__main__":
    main()
