//! Materialize a debt report into Beads issues.

use anyhow::{anyhow, Context, Result};
use serde::Serialize;
use serde_json::Value;
use std::path::Path;
use std::process::Command;

use super::output::category_str;
use super::types::DebtReport;

#[derive(Debug, Clone, Serialize)]
pub struct FiledDebtBeads {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub epic_id: Option<String>,
    pub task_ids: Vec<String>,
    pub debt_label: String,
    pub filed_hotspots: usize,
    pub message: String,
}

pub fn file(report: &DebtReport, project_dir: &Path) -> Result<FiledDebtBeads> {
    if report.hotspots.is_empty() {
        return Ok(FiledDebtBeads {
            epic_id: None,
            task_ids: Vec::new(),
            debt_label: report.summary.debt_label.as_str().to_string(),
            filed_hotspots: 0,
            message: "No hotspots to file.".into(),
        });
    }

    let epic_title = format!(
        "Debt triage: {} ({})",
        project_name(project_dir),
        report.summary.debt_label.as_str()
    );
    let epic_desc = format!(
        "Repo debt label: {}. {} findings across {} dead / {} dup / {} deps / {} hotspots. Generated by wh debt {}.",
        report.summary.debt_label.as_str(),
        report.summary.finding_count,
        report.summary.by_category.dead,
        report.summary.by_category.dup,
        report.summary.by_category.deps,
        report.summary.by_category.hotspots,
        report.generated_at,
    );
    let epic_id = create_issue(
        project_dir,
        &["create", "--type=epic"],
        &[
            ("--title", epic_title.as_str()),
            ("--description", epic_desc.as_str()),
            ("--priority", "2"),
            ("--labels", "debt"),
        ],
    )?;

    let mut task_ids = Vec::with_capacity(report.hotspots.len());
    for h in &report.hotspots {
        let desc = format!(
            "Rule: {} · confidence: {} · score: {:.2}\n\nCategory: {}\nEvidence: {}\n\nFiles: {}\n\nNext action: {}",
            h.rule_id,
            h.confidence.as_str(),
            h.score,
            category_str(h.category),
            super::output::evidence_one_liner(&h.evidence),
            if h.files.is_empty() {
                "(none)".into()
            } else {
                h.files.join(", ")
            },
            h.next_action,
        );
        let labels = format!("debt,{}", category_str(h.category));
        let task_id = create_issue(
            project_dir,
            &["create", "--type=task"],
            &[
                ("--parent", epic_id.as_str()),
                ("--title", h.title.as_str()),
                ("--description", desc.as_str()),
                ("--priority", "2"),
                ("--labels", labels.as_str()),
                (
                    "--acceptance",
                    "Finding resolved: this hotspot no longer appears in wh debt output at the chosen confidence threshold.",
                ),
            ],
        )?;
        task_ids.push(task_id);
    }

    Ok(FiledDebtBeads {
        epic_id: Some(epic_id.clone()),
        task_ids,
        debt_label: report.summary.debt_label.as_str().to_string(),
        filed_hotspots: report.hotspots.len(),
        message: format!(
            "Filed epic {} with {} child tasks.",
            epic_id,
            report.hotspots.len()
        ),
    })
}

fn create_issue(project_dir: &Path, prefix: &[&str], pairs: &[(&str, &str)]) -> Result<String> {
    let mut cmd = Command::new("bd");
    cmd.current_dir(project_dir).args(prefix);
    for (k, v) in pairs {
        cmd.arg(k).arg(v);
    }
    cmd.arg("--json");

    let output = cmd
        .output()
        .with_context(|| format!("failed to launch bd in {}", project_dir.display()))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr).trim().to_string();
        let stdout = String::from_utf8_lossy(&output.stdout).trim().to_string();
        let detail = if !stderr.is_empty() { stderr } else { stdout };
        return Err(anyhow!("bd create failed: {detail}"));
    }

    let value: Value = serde_json::from_slice(&output.stdout)
        .with_context(|| "bd create did not emit valid JSON")?;
    value
        .get("id")
        .and_then(|v| v.as_str())
        .map(|s| s.to_string())
        .ok_or_else(|| anyhow!("bd create JSON did not include an id field"))
}

fn project_name(project_dir: &Path) -> String {
    project_dir
        .file_name()
        .and_then(|s| s.to_str())
        .filter(|s| !s.is_empty())
        .unwrap_or("repo")
        .to_string()
}
