//! Human, prompt, and Beads formatters for a `DebtReport`.

use super::types::{Category, DebtReport, Evidence};

/// Compact terminal summary. ~20 lines for a healthy repo, caps at top.len().
pub fn format_human(report: &DebtReport) -> String {
    let mut lines: Vec<String> = Vec::new();

    lines.push(format!(
        "Debt: {} ({} findings — {} dead, {} dup, {} deps, {} hotspots)",
        report.summary.debt_label.as_str(),
        report.summary.finding_count,
        report.summary.by_category.dead,
        report.summary.by_category.dup,
        report.summary.by_category.deps,
        report.summary.by_category.hotspots,
    ));

    if report.hotspots.is_empty() {
        lines.push(String::new());
        lines.push(
            "No high-confidence findings. Repo looks clean to the debt detectors.".to_string(),
        );
        return lines.join("\n");
    }

    lines.push(String::new());
    lines.push(format!("Top {} hotspots:", report.hotspots.len()));

    for h in &report.hotspots {
        let cat = h.category.as_str();
        let conf = h.confidence.as_str();
        lines.push(format!(
            "  {rank:>2}. [{cat}/{conf}] {title}  (score {score:.2})",
            rank = h.rank,
            cat = cat,
            conf = conf,
            title = h.title,
            score = h.score,
        ));
        if !h.files.is_empty() {
            let preview = preview_files(&h.files, 3);
            lines.push(format!("      files: {preview}"));
        }
        lines.push(format!("      → {}", h.next_action));
    }

    lines.push(String::new());
    lines.push("Next:".to_string());
    lines.push("  wh debt --json            # stable machine-readable envelope".to_string());
    lines.push("  wh debt --prompt          # handoff block for another agent".to_string());
    lines.push("  wh debt --beads           # open an epic + child tasks in bd".to_string());

    lines.join("\n")
}

/// Compact remediation prompt for another agent. Target: ~2k tokens max.
pub fn format_prompt(report: &DebtReport) -> String {
    let mut s = String::new();
    s.push_str("# Debt triage handoff\n\n");
    s.push_str(&format!(
        "Repo debt label: {} ({} findings: {} dead, {} dup, {} deps, {} hotspots).\n",
        report.summary.debt_label.as_str(),
        report.summary.finding_count,
        report.summary.by_category.dead,
        report.summary.by_category.dup,
        report.summary.by_category.deps,
        report.summary.by_category.hotspots,
    ));
    s.push_str("Work the hotspots below in order. Each entry is deterministic and backed by evidence.\n\n");

    if report.hotspots.is_empty() {
        s.push_str("No hotspots. Nothing to do.\n");
        return s;
    }

    for h in &report.hotspots {
        s.push_str(&format!(
            "## {rank}. {title}\n",
            rank = h.rank,
            title = h.title
        ));
        s.push_str(&format!(
            "- rule: `{rule}`  ·  confidence: {conf}  ·  score: {score:.2}\n",
            rule = h.rule_id,
            conf = h.confidence.as_str(),
            score = h.score,
        ));
        if !h.files.is_empty() {
            s.push_str(&format!("- files: {}\n", h.files.join(", ")));
        }
        s.push_str(&format!("- evidence: {}\n", evidence_one_liner(&h.evidence)));
        s.push_str(&format!("- action: {}\n\n", h.next_action));
    }

    s.push_str("Rules: edit files listed above only. Do not expand scope beyond these hotspots. Report one diff per hotspot.\n");
    s
}

/// Shell commands that materialize the report as Beads issues. Emitted as
/// a single here-doc block so the user can pipe it to `sh` if they want.
pub fn format_beads(report: &DebtReport) -> String {
    let mut s = String::new();
    s.push_str("#!/bin/sh\n");
    s.push_str("# wh debt --beads: one epic + one child task per ranked hotspot.\n");
    s.push_str(&format!(
        "# Generated {} — schema v{}.\n\n",
        report.generated_at, report.schema_version
    ));

    if report.hotspots.is_empty() {
        s.push_str("echo 'No hotspots to file.'\n");
        return s;
    }

    s.push_str("set -eu\n");
    s.push_str(&format!(
        "EPIC=$(bd create --type=epic \\\n  --title=\"Debt triage: {label}\" \\\n  --description=\"Repo debt label: {label}. {count} findings across {dead} dead / {dup} dup / {deps} deps / {hot} hotspots. Generated by wh debt {when}.\" \\\n  --priority=2 --labels=debt --json | jq -r .id)\n\n",
        label = report.summary.debt_label.as_str(),
        count = report.summary.finding_count,
        dead = report.summary.by_category.dead,
        dup = report.summary.by_category.dup,
        deps = report.summary.by_category.deps,
        hot = report.summary.by_category.hotspots,
        when = report.generated_at,
    ));

    for h in &report.hotspots {
        let title = shell_escape(&h.title);
        let desc = shell_escape(&format!(
            "Rule: {rule} · confidence: {conf} · score: {score:.2}\n\nEvidence: {ev}\n\nFiles: {files}\n\nNext action: {next}",
            rule = h.rule_id,
            conf = h.confidence.as_str(),
            score = h.score,
            ev = evidence_one_liner(&h.evidence),
            files = h.files.join(", "),
            next = h.next_action,
        ));
        s.push_str(&format!(
            "bd create --type=task --parent=\"$EPIC\" \\\n  --title={title} \\\n  --description={desc} \\\n  --priority=2 --labels=debt --acceptance=\"Findings resolved: reduce score below threshold or remove from detector output.\"\n\n",
        ));
    }

    s.push_str("echo \"Filed epic $EPIC with ");
    s.push_str(&report.hotspots.len().to_string());
    s.push_str(" child tasks.\"\n");
    s
}

fn evidence_one_liner(e: &Evidence) -> String {
    match e {
        Evidence::ManifestEntry {
            snippet,
            references,
            ..
        } => format!("manifest entry `{snippet}` with {references} import references"),
        Evidence::SymbolDef {
            name,
            symbol_kind,
            references,
            locations,
        } => {
            let loc = locations
                .first()
                .map(|l| format!("{}:{}", l.file, l.line.unwrap_or(0)))
                .unwrap_or_default();
            format!("{symbol_kind} `{name}` at {loc} with {references} references")
        }
        Evidence::DuplicateCluster {
            normalized_lines,
            occurrences,
            ..
        } => format!("{occurrences} copies of a {normalized_lines}-line block"),
        Evidence::OrphanedFile { path, .. } => format!("file `{path}` is never imported"),
        Evidence::ChurnViolationIntersection {
            changes,
            violations,
            window_days,
            ..
        } => format!(
            "{changes} changes in {window_days}d × {violations} outstanding violations",
        ),
    }
}

fn shell_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for ch in s.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '$' => out.push_str("\\$"),
            '`' => out.push_str("\\`"),
            '\n' => out.push_str("\\n"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn preview_files(files: &[String], max: usize) -> String {
    if files.len() <= max {
        files.join(", ")
    } else {
        let taken: Vec<&String> = files.iter().take(max).collect();
        format!(
            "{}, ... +{}",
            taken
                .into_iter()
                .cloned()
                .collect::<Vec<_>>()
                .join(", "),
            files.len() - max
        )
    }
}

// Keep Category available for callers that want per-bucket rendering later.
#[allow(dead_code)]
pub fn category_str(c: Category) -> &'static str {
    c.as_str()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::debt::types::*;

    fn sample() -> DebtReport {
        DebtReport {
            schema_version: 1,
            generated_at: "2026-04-22T00:00:00Z".to_string(),
            project_dir: "/tmp/x".to_string(),
            summary: Summary {
                debt_label: DebtLabel::Moderate,
                hotspot_count: 1,
                finding_count: 1,
                by_category: BycatCounts {
                    dead: 1,
                    dup: 0,
                    deps: 0,
                    hotspots: 0,
                },
            },
            hotspots: vec![Hotspot {
                id: "h1".into(),
                category: Category::Dead,
                rule_id: "dead.unused_declared_deps".into(),
                title: "Unused declared dependency: requests-mock".into(),
                confidence: Confidence::High,
                rank: 1,
                score: 1.0,
                files: vec!["pyproject.toml".into()],
                evidence: Evidence::ManifestEntry {
                    snippet: "requests-mock = '^1.11'".into(),
                    references: 0,
                    locations: vec![Location {
                        file: "pyproject.toml".into(),
                        line: Some(23),
                    }],
                },
                next_action: "Remove requests-mock from pyproject.toml if truly unused.".into(),
            }],
            notes: vec![],
        }
    }

    #[test]
    fn human_formatter_mentions_hotspot_title_and_next() {
        let s = format_human(&sample());
        assert!(s.contains("Unused declared dependency"));
        assert!(s.contains("Remove requests-mock"));
        assert!(s.contains("Top 1 hotspots"));
    }

    #[test]
    fn prompt_formatter_caps_structure() {
        let s = format_prompt(&sample());
        assert!(s.starts_with("# Debt triage handoff"));
        assert!(s.contains("`dead.unused_declared_deps`"));
    }

    #[test]
    fn beads_formatter_emits_epic_and_child() {
        let s = format_beads(&sample());
        assert!(s.contains("--type=epic"));
        assert!(s.contains("--type=task"));
        assert!(s.contains("--parent=\"$EPIC\""));
    }
}
