//! `wh check` — scan source files and report rule violations.
//!
//! Signal handling:
//! - `pattern` with `match:` → regex scan, line-by-line.
//! - `ast` with `match:` → same scan, annotated as AST-flavoured in the
//!   report so readers know the check is still regex-backed until a
//!   dedicated tree-sitter query lives on the rule.
//! - `lint_proxy` → skipped with a note (verified via overlay configs
//!   generated by `wh tests`).
//! - `ai` → skipped (not deterministic).

use anyhow::Result;
use regex::Regex;
use serde_json::{json, Value};
use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

use crate::ast::AstLang;
use crate::detect::walk::SKIP_DIRS;
use crate::layers;
use crate::rules::ApprovedRule;

pub struct CheckOptions<'a> {
    pub project_dir: &'a Path,
    pub scan_paths: &'a [PathBuf],
    pub lang_filter: Option<&'a str>,
    pub rule_filter: Option<&'a [String]>,
}

pub fn run(opts: CheckOptions<'_>) -> Result<Value> {
    let project_dir = opts.project_dir;
    let whetstone_cfg = project_dir.join("whetstone").join("whetstone.yaml");
    let have_cfg = whetstone_cfg.exists() || project_dir.join("whetstone.yaml").exists();

    let rules: Vec<ApprovedRule> = if have_cfg {
        let merged = layers::resolve_merged(project_dir, opts.lang_filter, true, true, false);
        merged.merged.into_iter().map(|lr| lr.rule).collect()
    } else {
        let paths = layers::LayerPaths::for_project(project_dir);
        let (r, _) = crate::rules::load_approved_rules(&paths.project_rules_dir, opts.lang_filter);
        r
    };

    let rule_filter: Option<BTreeSet<&str>> = opts
        .rule_filter
        .map(|ids| ids.iter().map(String::as_str).collect());

    let rules: Vec<&ApprovedRule> = rules
        .iter()
        .filter(|r| rule_filter.as_ref().map(|set| set.contains(r.id.as_str())).unwrap_or(true))
        .collect();

    if rules.is_empty() {
        return Ok(json!({
            "status": "ok",
            "violations_count": 0,
            "files_scanned": 0,
            "rules_applied": 0,
            "violations": [],
            "skipped": [],
            "warnings": ["No approved rules match the supplied filters."],
        }));
    }

    let compiled = compile_rules(&rules);
    let mut violations: Vec<Value> = Vec::new();
    let mut skipped: Vec<Value> = Vec::new();
    let mut warnings: Vec<String> = Vec::new();
    let mut files_scanned: usize = 0;

    for crule in &compiled {
        for note in &crule.notes {
            skipped.push(json!({"rule_id": crule.rule.id, "reason": note}));
        }
    }

    let files = discover_source_files(opts.scan_paths);
    for (path, lang) in &files {
        if let Some(filter) = opts.lang_filter {
            if lang.as_str() != filter {
                continue;
            }
        }
        let text = match std::fs::read_to_string(path) {
            Ok(t) => t,
            Err(e) => {
                warnings.push(format!("Failed to read {}: {e}", path.display()));
                continue;
            }
        };
        files_scanned += 1;

        for crule in &compiled {
            if !rule_applies_to_language(&crule.rule.language, lang) {
                continue;
            }
            for sig in &crule.signals {
                let hits = apply_signal(sig, &text);
                for hit in hits {
                    violations.push(json!({
                        "rule_id": crule.rule.id,
                        "severity": crule.rule.severity,
                        "category": crule.rule.category,
                        "description": first_line(&crule.rule.description),
                        "source_url": crule.rule.source_url,
                        "language": lang.as_str(),
                        "signal_id": sig.signal_id,
                        "signal_strategy": sig.strategy,
                        "signal_description": sig.description,
                        "file": path.display().to_string(),
                        "line": hit.line,
                        "column": hit.column,
                        "match": hit.text,
                    }));
                }
            }
        }
    }

    let violations_count = violations.len() as i64;
    Ok(json!({
        "status": if violations_count == 0 { "ok" } else { "violations_found" },
        "violations_count": violations_count,
        "files_scanned": files_scanned,
        "rules_applied": rules.len(),
        "violations": violations,
        "skipped": skipped,
        "warnings": warnings,
    }))
}

// ── Human formatter ──

pub fn format_human_output(result: &Value) -> String {
    let mut out = String::new();
    let count = result
        .get("violations_count")
        .and_then(|v| v.as_i64())
        .unwrap_or(0);
    let files = result
        .get("files_scanned")
        .and_then(|v| v.as_i64())
        .unwrap_or(0);
    let rules = result
        .get("rules_applied")
        .and_then(|v| v.as_i64())
        .unwrap_or(0);

    if count == 0 {
        out.push_str(&format!(
            "wh check: no violations ({rules} rule(s), {files} file(s))\n"
        ));
        return out;
    }

    out.push_str(&format!(
        "wh check: {count} violation(s) across {files} file(s) against {rules} rule(s)\n"
    ));
    if let Some(arr) = result.get("violations").and_then(|v| v.as_array()) {
        for v in arr {
            let file = v.get("file").and_then(|v| v.as_str()).unwrap_or("?");
            let line = v.get("line").and_then(|v| v.as_i64()).unwrap_or(0);
            let sev = v.get("severity").and_then(|v| v.as_str()).unwrap_or("?");
            let id = v.get("rule_id").and_then(|v| v.as_str()).unwrap_or("?");
            let desc = v.get("description").and_then(|v| v.as_str()).unwrap_or("");
            out.push_str(&format!("  {file}:{line}: [{sev}] {id} — {desc}\n"));
        }
    }
    out
}

// ── Internal types ──

struct CompiledRule<'a> {
    rule: &'a ApprovedRule,
    signals: Vec<CompiledSignal>,
    notes: Vec<String>,
}

struct CompiledSignal {
    signal_id: String,
    description: String,
    strategy: String,
    regex: Option<Regex>,
}

struct SignalHit {
    line: usize,
    column: usize,
    text: String,
}

fn compile_rules<'a>(rules: &[&'a ApprovedRule]) -> Vec<CompiledRule<'a>> {
    let mut out = Vec::new();
    for rule in rules {
        let mut signals = Vec::new();
        let mut notes = Vec::new();
        for sig in &rule.signals {
            match sig.strategy.as_str() {
                "pattern" | "ast" => {
                    if let Some(ref pat) = sig.match_pattern {
                        match Regex::new(pat) {
                            Ok(re) => signals.push(CompiledSignal {
                                signal_id: sig.id.clone(),
                                description: sig.description.clone(),
                                strategy: sig.strategy.clone(),
                                regex: Some(re),
                            }),
                            Err(e) => {
                                notes.push(format!(
                                    "signal {}: invalid regex `{}` — {e}",
                                    sig.id, pat
                                ));
                            }
                        }
                    } else {
                        notes.push(format!(
                            "signal {}: {} signal has no `match:` pattern; cannot enforce",
                            sig.id, sig.strategy
                        ));
                    }
                }
                "lint_proxy" => {
                    notes.push(format!(
                        "signal {}: lint_proxy delegated to linter config (run `wh tests`)",
                        sig.id
                    ));
                }
                "ai" => {
                    notes.push(format!(
                        "signal {}: ai signal evaluated via `wh eval run` only",
                        sig.id
                    ));
                }
                other => notes.push(format!("signal {}: unknown strategy {other}", sig.id)),
            }
        }
        out.push(CompiledRule {
            rule,
            signals,
            notes,
        });
    }
    out
}

fn apply_signal(sig: &CompiledSignal, text: &str) -> Vec<SignalHit> {
    let re = match &sig.regex {
        Some(r) => r,
        None => return Vec::new(),
    };
    let mut hits = Vec::new();
    for (i, line) in text.lines().enumerate() {
        if let Some(m) = re.find(line) {
            hits.push(SignalHit {
                line: i + 1,
                column: m.start() + 1,
                text: line.trim().to_string(),
            });
        }
    }
    hits
}

// ── File discovery ──

fn discover_source_files(roots: &[PathBuf]) -> Vec<(PathBuf, AstLang)> {
    let mut out = Vec::new();
    for root in roots {
        for entry in walkdir::WalkDir::new(root)
            .into_iter()
            .filter_entry(|e| {
                if e.depth() == 0 {
                    return true;
                }
                let name = e.file_name().to_string_lossy();
                !SKIP_DIRS.iter().any(|d| *d == name)
            })
            .filter_map(|e| e.ok())
        {
            if !entry.file_type().is_file() {
                continue;
            }
            if let Some(ext) = entry.path().extension().and_then(|e| e.to_str()) {
                if let Some(lang) = AstLang::from_extension(ext) {
                    out.push((entry.into_path(), lang));
                }
            }
        }
    }
    out
}

fn rule_applies_to_language(rule_lang: &str, file_lang: &AstLang) -> bool {
    match file_lang {
        AstLang::Python => rule_lang == "python",
        AstLang::TypeScript => rule_lang == "typescript" || rule_lang == "javascript",
        AstLang::Rust => rule_lang == "rust",
    }
}

fn first_line(text: &str) -> String {
    text.lines().next().unwrap_or("").to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;

    fn rule_with_regex(id: &str, lang: &str, match_pattern: &str) -> ApprovedRule {
        ApprovedRule {
            id: id.into(),
            severity: "must".into(),
            confidence: "high".into(),
            category: "default".into(),
            description: "test rule".into(),
            source_url: "https://example".into(),
            source_name: "demo".into(),
            language: lang.into(),
            signals: vec![crate::rules::ApprovedSignal {
                id: "s1".into(),
                strategy: "pattern".into(),
                description: "pattern signal".into(),
                weight: "required".into(),
                match_pattern: Some(match_pattern.into()),
            }],
            golden_examples: Vec::new(),
            risk: None,
            linter_gap: None,
            deterministic_pass_threshold: None,
            deterministic_fail_threshold: None,
            ai_eval: None,
        }
    }

    #[test]
    fn pattern_signal_fires_on_match() {
        let rule = rule_with_regex("demo.unwrap", "rust", r"\.unwrap\(\)");
        let rules = vec![&rule];
        let compiled = compile_rules(&rules);
        let hits = apply_signal(&compiled[0].signals[0], "let v = x.unwrap();\n");
        assert_eq!(hits.len(), 1);
        assert_eq!(hits[0].line, 1);
    }

    #[test]
    fn invalid_regex_skipped_with_note() {
        let mut rule = rule_with_regex("demo.bad", "python", "valid");
        rule.signals[0].match_pattern = Some("[invalid".into());
        let rules = vec![&rule];
        let compiled = compile_rules(&rules);
        assert!(compiled[0].signals.is_empty(), "invalid regex should not produce a signal");
        assert!(compiled[0].notes.iter().any(|n| n.contains("invalid regex")));
    }

    #[test]
    fn discover_filters_by_extension_and_skip_dirs() {
        let tmp = tempdir();
        std::fs::create_dir_all(tmp.join("src")).unwrap();
        std::fs::create_dir_all(tmp.join("node_modules")).unwrap();
        write_file(&tmp.join("src/a.py"), "x = 1\n");
        write_file(&tmp.join("src/b.rs"), "fn main() {}\n");
        write_file(&tmp.join("node_modules/c.ts"), "const x = 1;\n");
        let files = discover_source_files(std::slice::from_ref(&tmp));
        let names: Vec<_> = files.iter().map(|(p, _)| p.file_name().unwrap().to_string_lossy().to_string()).collect();
        assert!(names.contains(&"a.py".to_string()));
        assert!(names.contains(&"b.rs".to_string()));
        assert!(!names.contains(&"c.ts".to_string()), "node_modules should be skipped");
    }

    fn tempdir() -> PathBuf {
        let base = std::env::temp_dir().join(format!(
            "wh-check-test-{}",
            std::process::id() as u128 * 1_000_000 + rand_part()
        ));
        std::fs::create_dir_all(&base).unwrap();
        base
    }

    fn rand_part() -> u128 {
        use std::time::{SystemTime, UNIX_EPOCH};
        SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0)
    }

    fn write_file(path: &Path, body: &str) {
        let mut f = std::fs::File::create(path).unwrap();
        f.write_all(body.as_bytes()).unwrap();
    }
}
